/*
 * WARNING: this file has been generated by
 * Hime Parser Generator
 */

//! Contains the supported Unicode blocks

use super::UnicodeBlock;
use std::collections::HashMap;

/// The unicode block BasicLatin
pub const BASIC_LATIN: &'static str = "BasicLatin";

/// The unicode block Latin-1Supplement
pub const LATIN_1SUPPLEMENT: &'static str = "Latin-1Supplement";

/// The unicode block LatinExtended-A
pub const LATIN_EXTENDED_A: &'static str = "LatinExtended-A";

/// The unicode block LatinExtended-B
pub const LATIN_EXTENDED_B: &'static str = "LatinExtended-B";

/// The unicode block IPAExtensions
pub const IPAEXTENSIONS: &'static str = "IPAExtensions";

/// The unicode block SpacingModifierLetters
pub const SPACING_MODIFIER_LETTERS: &'static str = "SpacingModifierLetters";

/// The unicode block CombiningDiacriticalMarks
pub const COMBINING_DIACRITICAL_MARKS: &'static str = "CombiningDiacriticalMarks";

/// The unicode block GreekandCoptic
pub const GREEKAND_COPTIC: &'static str = "GreekandCoptic";

/// The unicode block Cyrillic
pub const CYRILLIC: &'static str = "Cyrillic";

/// The unicode block CyrillicSupplement
pub const CYRILLIC_SUPPLEMENT: &'static str = "CyrillicSupplement";

/// The unicode block Armenian
pub const ARMENIAN: &'static str = "Armenian";

/// The unicode block Hebrew
pub const HEBREW: &'static str = "Hebrew";

/// The unicode block Arabic
pub const ARABIC: &'static str = "Arabic";

/// The unicode block Syriac
pub const SYRIAC: &'static str = "Syriac";

/// The unicode block ArabicSupplement
pub const ARABIC_SUPPLEMENT: &'static str = "ArabicSupplement";

/// The unicode block Thaana
pub const THAANA: &'static str = "Thaana";

/// The unicode block NKo
pub const NKO: &'static str = "NKo";

/// The unicode block Samaritan
pub const SAMARITAN: &'static str = "Samaritan";

/// The unicode block Mandaic
pub const MANDAIC: &'static str = "Mandaic";

/// The unicode block SyriacSupplement
pub const SYRIAC_SUPPLEMENT: &'static str = "SyriacSupplement";

/// The unicode block ArabicExtended-A
pub const ARABIC_EXTENDED_A: &'static str = "ArabicExtended-A";

/// The unicode block Devanagari
pub const DEVANAGARI: &'static str = "Devanagari";

/// The unicode block Bengali
pub const BENGALI: &'static str = "Bengali";

/// The unicode block Gurmukhi
pub const GURMUKHI: &'static str = "Gurmukhi";

/// The unicode block Gujarati
pub const GUJARATI: &'static str = "Gujarati";

/// The unicode block Oriya
pub const ORIYA: &'static str = "Oriya";

/// The unicode block Tamil
pub const TAMIL: &'static str = "Tamil";

/// The unicode block Telugu
pub const TELUGU: &'static str = "Telugu";

/// The unicode block Kannada
pub const KANNADA: &'static str = "Kannada";

/// The unicode block Malayalam
pub const MALAYALAM: &'static str = "Malayalam";

/// The unicode block Sinhala
pub const SINHALA: &'static str = "Sinhala";

/// The unicode block Thai
pub const THAI: &'static str = "Thai";

/// The unicode block Lao
pub const LAO: &'static str = "Lao";

/// The unicode block Tibetan
pub const TIBETAN: &'static str = "Tibetan";

/// The unicode block Myanmar
pub const MYANMAR: &'static str = "Myanmar";

/// The unicode block Georgian
pub const GEORGIAN: &'static str = "Georgian";

/// The unicode block HangulJamo
pub const HANGUL_JAMO: &'static str = "HangulJamo";

/// The unicode block Ethiopic
pub const ETHIOPIC: &'static str = "Ethiopic";

/// The unicode block EthiopicSupplement
pub const ETHIOPIC_SUPPLEMENT: &'static str = "EthiopicSupplement";

/// The unicode block Cherokee
pub const CHEROKEE: &'static str = "Cherokee";

/// The unicode block UnifiedCanadianAboriginalSyllabics
pub const UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS: &'static str =
    "UnifiedCanadianAboriginalSyllabics";

/// The unicode block Ogham
pub const OGHAM: &'static str = "Ogham";

/// The unicode block Runic
pub const RUNIC: &'static str = "Runic";

/// The unicode block Tagalog
pub const TAGALOG: &'static str = "Tagalog";

/// The unicode block Hanunoo
pub const HANUNOO: &'static str = "Hanunoo";

/// The unicode block Buhid
pub const BUHID: &'static str = "Buhid";

/// The unicode block Tagbanwa
pub const TAGBANWA: &'static str = "Tagbanwa";

/// The unicode block Khmer
pub const KHMER: &'static str = "Khmer";

/// The unicode block Mongolian
pub const MONGOLIAN: &'static str = "Mongolian";

/// The unicode block UnifiedCanadianAboriginalSyllabicsExtended
pub const UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED: &'static str =
    "UnifiedCanadianAboriginalSyllabicsExtended";

/// The unicode block Limbu
pub const LIMBU: &'static str = "Limbu";

/// The unicode block TaiLe
pub const TAI_LE: &'static str = "TaiLe";

/// The unicode block NewTaiLue
pub const NEW_TAI_LUE: &'static str = "NewTaiLue";

/// The unicode block KhmerSymbols
pub const KHMER_SYMBOLS: &'static str = "KhmerSymbols";

/// The unicode block Buginese
pub const BUGINESE: &'static str = "Buginese";

/// The unicode block TaiTham
pub const TAI_THAM: &'static str = "TaiTham";

/// The unicode block CombiningDiacriticalMarksExtended
pub const COMBINING_DIACRITICAL_MARKS_EXTENDED: &'static str = "CombiningDiacriticalMarksExtended";

/// The unicode block Balinese
pub const BALINESE: &'static str = "Balinese";

/// The unicode block Sundanese
pub const SUNDANESE: &'static str = "Sundanese";

/// The unicode block Batak
pub const BATAK: &'static str = "Batak";

/// The unicode block Lepcha
pub const LEPCHA: &'static str = "Lepcha";

/// The unicode block OlChiki
pub const OL_CHIKI: &'static str = "OlChiki";

/// The unicode block CyrillicExtended-C
pub const CYRILLIC_EXTENDED_C: &'static str = "CyrillicExtended-C";

/// The unicode block SundaneseSupplement
pub const SUNDANESE_SUPPLEMENT: &'static str = "SundaneseSupplement";

/// The unicode block VedicExtensions
pub const VEDIC_EXTENSIONS: &'static str = "VedicExtensions";

/// The unicode block PhoneticExtensions
pub const PHONETIC_EXTENSIONS: &'static str = "PhoneticExtensions";

/// The unicode block PhoneticExtensionsSupplement
pub const PHONETIC_EXTENSIONS_SUPPLEMENT: &'static str = "PhoneticExtensionsSupplement";

/// The unicode block CombiningDiacriticalMarksSupplement
pub const COMBINING_DIACRITICAL_MARKS_SUPPLEMENT: &'static str =
    "CombiningDiacriticalMarksSupplement";

/// The unicode block LatinExtendedAdditional
pub const LATIN_EXTENDED_ADDITIONAL: &'static str = "LatinExtendedAdditional";

/// The unicode block GreekExtended
pub const GREEK_EXTENDED: &'static str = "GreekExtended";

/// The unicode block GeneralPunctuation
pub const GENERAL_PUNCTUATION: &'static str = "GeneralPunctuation";

/// The unicode block SuperscriptsandSubscripts
pub const SUPERSCRIPTSAND_SUBSCRIPTS: &'static str = "SuperscriptsandSubscripts";

/// The unicode block CurrencySymbols
pub const CURRENCY_SYMBOLS: &'static str = "CurrencySymbols";

/// The unicode block CombiningDiacriticalMarksforSymbols
pub const COMBINING_DIACRITICAL_MARKSFOR_SYMBOLS: &'static str =
    "CombiningDiacriticalMarksforSymbols";

/// The unicode block LetterlikeSymbols
pub const LETTERLIKE_SYMBOLS: &'static str = "LetterlikeSymbols";

/// The unicode block NumberForms
pub const NUMBER_FORMS: &'static str = "NumberForms";

/// The unicode block Arrows
pub const ARROWS: &'static str = "Arrows";

/// The unicode block MathematicalOperators
pub const MATHEMATICAL_OPERATORS: &'static str = "MathematicalOperators";

/// The unicode block MiscellaneousTechnical
pub const MISCELLANEOUS_TECHNICAL: &'static str = "MiscellaneousTechnical";

/// The unicode block ControlPictures
pub const CONTROL_PICTURES: &'static str = "ControlPictures";

/// The unicode block OpticalCharacterRecognition
pub const OPTICAL_CHARACTER_RECOGNITION: &'static str = "OpticalCharacterRecognition";

/// The unicode block EnclosedAlphanumerics
pub const ENCLOSED_ALPHANUMERICS: &'static str = "EnclosedAlphanumerics";

/// The unicode block BoxDrawing
pub const BOX_DRAWING: &'static str = "BoxDrawing";

/// The unicode block BlockElements
pub const BLOCK_ELEMENTS: &'static str = "BlockElements";

/// The unicode block GeometricShapes
pub const GEOMETRIC_SHAPES: &'static str = "GeometricShapes";

/// The unicode block MiscellaneousSymbols
pub const MISCELLANEOUS_SYMBOLS: &'static str = "MiscellaneousSymbols";

/// The unicode block Dingbats
pub const DINGBATS: &'static str = "Dingbats";

/// The unicode block MiscellaneousMathematicalSymbols-A
pub const MISCELLANEOUS_MATHEMATICAL_SYMBOLS_A: &'static str = "MiscellaneousMathematicalSymbols-A";

/// The unicode block SupplementalArrows-A
pub const SUPPLEMENTAL_ARROWS_A: &'static str = "SupplementalArrows-A";

/// The unicode block BraillePatterns
pub const BRAILLE_PATTERNS: &'static str = "BraillePatterns";

/// The unicode block SupplementalArrows-B
pub const SUPPLEMENTAL_ARROWS_B: &'static str = "SupplementalArrows-B";

/// The unicode block MiscellaneousMathematicalSymbols-B
pub const MISCELLANEOUS_MATHEMATICAL_SYMBOLS_B: &'static str = "MiscellaneousMathematicalSymbols-B";

/// The unicode block SupplementalMathematicalOperators
pub const SUPPLEMENTAL_MATHEMATICAL_OPERATORS: &'static str = "SupplementalMathematicalOperators";

/// The unicode block MiscellaneousSymbolsandArrows
pub const MISCELLANEOUS_SYMBOLSAND_ARROWS: &'static str = "MiscellaneousSymbolsandArrows";

/// The unicode block Glagolitic
pub const GLAGOLITIC: &'static str = "Glagolitic";

/// The unicode block LatinExtended-C
pub const LATIN_EXTENDED_C: &'static str = "LatinExtended-C";

/// The unicode block Coptic
pub const COPTIC: &'static str = "Coptic";

/// The unicode block GeorgianSupplement
pub const GEORGIAN_SUPPLEMENT: &'static str = "GeorgianSupplement";

/// The unicode block Tifinagh
pub const TIFINAGH: &'static str = "Tifinagh";

/// The unicode block EthiopicExtended
pub const ETHIOPIC_EXTENDED: &'static str = "EthiopicExtended";

/// The unicode block CyrillicExtended-A
pub const CYRILLIC_EXTENDED_A: &'static str = "CyrillicExtended-A";

/// The unicode block SupplementalPunctuation
pub const SUPPLEMENTAL_PUNCTUATION: &'static str = "SupplementalPunctuation";

/// The unicode block CJKRadicalsSupplement
pub const CJKRADICALS_SUPPLEMENT: &'static str = "CJKRadicalsSupplement";

/// The unicode block KangxiRadicals
pub const KANGXI_RADICALS: &'static str = "KangxiRadicals";

/// The unicode block IdeographicDescriptionCharacters
pub const IDEOGRAPHIC_DESCRIPTION_CHARACTERS: &'static str = "IdeographicDescriptionCharacters";

/// The unicode block CJKSymbolsandPunctuation
pub const CJKSYMBOLSAND_PUNCTUATION: &'static str = "CJKSymbolsandPunctuation";

/// The unicode block Hiragana
pub const HIRAGANA: &'static str = "Hiragana";

/// The unicode block Katakana
pub const KATAKANA: &'static str = "Katakana";

/// The unicode block Bopomofo
pub const BOPOMOFO: &'static str = "Bopomofo";

/// The unicode block HangulCompatibilityJamo
pub const HANGUL_COMPATIBILITY_JAMO: &'static str = "HangulCompatibilityJamo";

/// The unicode block Kanbun
pub const KANBUN: &'static str = "Kanbun";

/// The unicode block BopomofoExtended
pub const BOPOMOFO_EXTENDED: &'static str = "BopomofoExtended";

/// The unicode block CJKStrokes
pub const CJKSTROKES: &'static str = "CJKStrokes";

/// The unicode block KatakanaPhoneticExtensions
pub const KATAKANA_PHONETIC_EXTENSIONS: &'static str = "KatakanaPhoneticExtensions";

/// The unicode block EnclosedCJKLettersandMonths
pub const ENCLOSED_CJKLETTERSAND_MONTHS: &'static str = "EnclosedCJKLettersandMonths";

/// The unicode block CJKCompatibility
pub const CJKCOMPATIBILITY: &'static str = "CJKCompatibility";

/// The unicode block CJKUnifiedIdeographsExtensionA
pub const CJKUNIFIED_IDEOGRAPHS_EXTENSION_A: &'static str = "CJKUnifiedIdeographsExtensionA";

/// The unicode block YijingHexagramSymbols
pub const YIJING_HEXAGRAM_SYMBOLS: &'static str = "YijingHexagramSymbols";

/// The unicode block CJKUnifiedIdeographs
pub const CJKUNIFIED_IDEOGRAPHS: &'static str = "CJKUnifiedIdeographs";

/// The unicode block YiSyllables
pub const YI_SYLLABLES: &'static str = "YiSyllables";

/// The unicode block YiRadicals
pub const YI_RADICALS: &'static str = "YiRadicals";

/// The unicode block Lisu
pub const LISU: &'static str = "Lisu";

/// The unicode block Vai
pub const VAI: &'static str = "Vai";

/// The unicode block CyrillicExtended-B
pub const CYRILLIC_EXTENDED_B: &'static str = "CyrillicExtended-B";

/// The unicode block Bamum
pub const BAMUM: &'static str = "Bamum";

/// The unicode block ModifierToneLetters
pub const MODIFIER_TONE_LETTERS: &'static str = "ModifierToneLetters";

/// The unicode block LatinExtended-D
pub const LATIN_EXTENDED_D: &'static str = "LatinExtended-D";

/// The unicode block SylotiNagri
pub const SYLOTI_NAGRI: &'static str = "SylotiNagri";

/// The unicode block CommonIndicNumberForms
pub const COMMON_INDIC_NUMBER_FORMS: &'static str = "CommonIndicNumberForms";

/// The unicode block Phags-pa
pub const PHAGS_PA: &'static str = "Phags-pa";

/// The unicode block Saurashtra
pub const SAURASHTRA: &'static str = "Saurashtra";

/// The unicode block DevanagariExtended
pub const DEVANAGARI_EXTENDED: &'static str = "DevanagariExtended";

/// The unicode block KayahLi
pub const KAYAH_LI: &'static str = "KayahLi";

/// The unicode block Rejang
pub const REJANG: &'static str = "Rejang";

/// The unicode block HangulJamoExtended-A
pub const HANGUL_JAMO_EXTENDED_A: &'static str = "HangulJamoExtended-A";

/// The unicode block Javanese
pub const JAVANESE: &'static str = "Javanese";

/// The unicode block MyanmarExtended-B
pub const MYANMAR_EXTENDED_B: &'static str = "MyanmarExtended-B";

/// The unicode block Cham
pub const CHAM: &'static str = "Cham";

/// The unicode block MyanmarExtended-A
pub const MYANMAR_EXTENDED_A: &'static str = "MyanmarExtended-A";

/// The unicode block TaiViet
pub const TAI_VIET: &'static str = "TaiViet";

/// The unicode block MeeteiMayekExtensions
pub const MEETEI_MAYEK_EXTENSIONS: &'static str = "MeeteiMayekExtensions";

/// The unicode block EthiopicExtended-A
pub const ETHIOPIC_EXTENDED_A: &'static str = "EthiopicExtended-A";

/// The unicode block LatinExtended-E
pub const LATIN_EXTENDED_E: &'static str = "LatinExtended-E";

/// The unicode block CherokeeSupplement
pub const CHEROKEE_SUPPLEMENT: &'static str = "CherokeeSupplement";

/// The unicode block MeeteiMayek
pub const MEETEI_MAYEK: &'static str = "MeeteiMayek";

/// The unicode block HangulSyllables
pub const HANGUL_SYLLABLES: &'static str = "HangulSyllables";

/// The unicode block HangulJamoExtended-B
pub const HANGUL_JAMO_EXTENDED_B: &'static str = "HangulJamoExtended-B";

/// The unicode block PrivateUseArea
pub const PRIVATE_USE_AREA: &'static str = "PrivateUseArea";

/// The unicode block CJKCompatibilityIdeographs
pub const CJKCOMPATIBILITY_IDEOGRAPHS: &'static str = "CJKCompatibilityIdeographs";

/// The unicode block AlphabeticPresentationForms
pub const ALPHABETIC_PRESENTATION_FORMS: &'static str = "AlphabeticPresentationForms";

/// The unicode block ArabicPresentationForms-A
pub const ARABIC_PRESENTATION_FORMS_A: &'static str = "ArabicPresentationForms-A";

/// The unicode block VariationSelectors
pub const VARIATION_SELECTORS: &'static str = "VariationSelectors";

/// The unicode block VerticalForms
pub const VERTICAL_FORMS: &'static str = "VerticalForms";

/// The unicode block CombiningHalfMarks
pub const COMBINING_HALF_MARKS: &'static str = "CombiningHalfMarks";

/// The unicode block CJKCompatibilityForms
pub const CJKCOMPATIBILITY_FORMS: &'static str = "CJKCompatibilityForms";

/// The unicode block SmallFormVariants
pub const SMALL_FORM_VARIANTS: &'static str = "SmallFormVariants";

/// The unicode block ArabicPresentationForms-B
pub const ARABIC_PRESENTATION_FORMS_B: &'static str = "ArabicPresentationForms-B";

/// The unicode block HalfwidthandFullwidthForms
pub const HALFWIDTHAND_FULLWIDTH_FORMS: &'static str = "HalfwidthandFullwidthForms";

/// The unicode block Specials
pub const SPECIALS: &'static str = "Specials";

/// The unicode block LinearBSyllabary
pub const LINEAR_BSYLLABARY: &'static str = "LinearBSyllabary";

/// The unicode block LinearBIdeograms
pub const LINEAR_BIDEOGRAMS: &'static str = "LinearBIdeograms";

/// The unicode block AegeanNumbers
pub const AEGEAN_NUMBERS: &'static str = "AegeanNumbers";

/// The unicode block AncientGreekNumbers
pub const ANCIENT_GREEK_NUMBERS: &'static str = "AncientGreekNumbers";

/// The unicode block AncientSymbols
pub const ANCIENT_SYMBOLS: &'static str = "AncientSymbols";

/// The unicode block PhaistosDisc
pub const PHAISTOS_DISC: &'static str = "PhaistosDisc";

/// The unicode block Lycian
pub const LYCIAN: &'static str = "Lycian";

/// The unicode block Carian
pub const CARIAN: &'static str = "Carian";

/// The unicode block CopticEpactNumbers
pub const COPTIC_EPACT_NUMBERS: &'static str = "CopticEpactNumbers";

/// The unicode block OldItalic
pub const OLD_ITALIC: &'static str = "OldItalic";

/// The unicode block Gothic
pub const GOTHIC: &'static str = "Gothic";

/// The unicode block OldPermic
pub const OLD_PERMIC: &'static str = "OldPermic";

/// The unicode block Ugaritic
pub const UGARITIC: &'static str = "Ugaritic";

/// The unicode block OldPersian
pub const OLD_PERSIAN: &'static str = "OldPersian";

/// The unicode block Deseret
pub const DESERET: &'static str = "Deseret";

/// The unicode block Shavian
pub const SHAVIAN: &'static str = "Shavian";

/// The unicode block Osmanya
pub const OSMANYA: &'static str = "Osmanya";

/// The unicode block Osage
pub const OSAGE: &'static str = "Osage";

/// The unicode block Elbasan
pub const ELBASAN: &'static str = "Elbasan";

/// The unicode block CaucasianAlbanian
pub const CAUCASIAN_ALBANIAN: &'static str = "CaucasianAlbanian";

/// The unicode block LinearA
pub const LINEAR_A: &'static str = "LinearA";

/// The unicode block CypriotSyllabary
pub const CYPRIOT_SYLLABARY: &'static str = "CypriotSyllabary";

/// The unicode block ImperialAramaic
pub const IMPERIAL_ARAMAIC: &'static str = "ImperialAramaic";

/// The unicode block Palmyrene
pub const PALMYRENE: &'static str = "Palmyrene";

/// The unicode block Nabataean
pub const NABATAEAN: &'static str = "Nabataean";

/// The unicode block Hatran
pub const HATRAN: &'static str = "Hatran";

/// The unicode block Phoenician
pub const PHOENICIAN: &'static str = "Phoenician";

/// The unicode block Lydian
pub const LYDIAN: &'static str = "Lydian";

/// The unicode block MeroiticHieroglyphs
pub const MEROITIC_HIEROGLYPHS: &'static str = "MeroiticHieroglyphs";

/// The unicode block MeroiticCursive
pub const MEROITIC_CURSIVE: &'static str = "MeroiticCursive";

/// The unicode block Kharoshthi
pub const KHAROSHTHI: &'static str = "Kharoshthi";

/// The unicode block OldSouthArabian
pub const OLD_SOUTH_ARABIAN: &'static str = "OldSouthArabian";

/// The unicode block OldNorthArabian
pub const OLD_NORTH_ARABIAN: &'static str = "OldNorthArabian";

/// The unicode block Manichaean
pub const MANICHAEAN: &'static str = "Manichaean";

/// The unicode block Avestan
pub const AVESTAN: &'static str = "Avestan";

/// The unicode block InscriptionalParthian
pub const INSCRIPTIONAL_PARTHIAN: &'static str = "InscriptionalParthian";

/// The unicode block InscriptionalPahlavi
pub const INSCRIPTIONAL_PAHLAVI: &'static str = "InscriptionalPahlavi";

/// The unicode block PsalterPahlavi
pub const PSALTER_PAHLAVI: &'static str = "PsalterPahlavi";

/// The unicode block OldTurkic
pub const OLD_TURKIC: &'static str = "OldTurkic";

/// The unicode block OldHungarian
pub const OLD_HUNGARIAN: &'static str = "OldHungarian";

/// The unicode block RumiNumeralSymbols
pub const RUMI_NUMERAL_SYMBOLS: &'static str = "RumiNumeralSymbols";

/// The unicode block Brahmi
pub const BRAHMI: &'static str = "Brahmi";

/// The unicode block Kaithi
pub const KAITHI: &'static str = "Kaithi";

/// The unicode block SoraSompeng
pub const SORA_SOMPENG: &'static str = "SoraSompeng";

/// The unicode block Chakma
pub const CHAKMA: &'static str = "Chakma";

/// The unicode block Mahajani
pub const MAHAJANI: &'static str = "Mahajani";

/// The unicode block Sharada
pub const SHARADA: &'static str = "Sharada";

/// The unicode block SinhalaArchaicNumbers
pub const SINHALA_ARCHAIC_NUMBERS: &'static str = "SinhalaArchaicNumbers";

/// The unicode block Khojki
pub const KHOJKI: &'static str = "Khojki";

/// The unicode block Multani
pub const MULTANI: &'static str = "Multani";

/// The unicode block Khudawadi
pub const KHUDAWADI: &'static str = "Khudawadi";

/// The unicode block Grantha
pub const GRANTHA: &'static str = "Grantha";

/// The unicode block Newa
pub const NEWA: &'static str = "Newa";

/// The unicode block Tirhuta
pub const TIRHUTA: &'static str = "Tirhuta";

/// The unicode block Siddham
pub const SIDDHAM: &'static str = "Siddham";

/// The unicode block Modi
pub const MODI: &'static str = "Modi";

/// The unicode block MongolianSupplement
pub const MONGOLIAN_SUPPLEMENT: &'static str = "MongolianSupplement";

/// The unicode block Takri
pub const TAKRI: &'static str = "Takri";

/// The unicode block Ahom
pub const AHOM: &'static str = "Ahom";

/// The unicode block WarangCiti
pub const WARANG_CITI: &'static str = "WarangCiti";

/// The unicode block ZanabazarSquare
pub const ZANABAZAR_SQUARE: &'static str = "ZanabazarSquare";

/// The unicode block Soyombo
pub const SOYOMBO: &'static str = "Soyombo";

/// The unicode block PauCinHau
pub const PAU_CIN_HAU: &'static str = "PauCinHau";

/// The unicode block Bhaiksuki
pub const BHAIKSUKI: &'static str = "Bhaiksuki";

/// The unicode block Marchen
pub const MARCHEN: &'static str = "Marchen";

/// The unicode block MasaramGondi
pub const MASARAM_GONDI: &'static str = "MasaramGondi";

/// The unicode block Cuneiform
pub const CUNEIFORM: &'static str = "Cuneiform";

/// The unicode block CuneiformNumbersandPunctuation
pub const CUNEIFORM_NUMBERSAND_PUNCTUATION: &'static str = "CuneiformNumbersandPunctuation";

/// The unicode block EarlyDynasticCuneiform
pub const EARLY_DYNASTIC_CUNEIFORM: &'static str = "EarlyDynasticCuneiform";

/// The unicode block EgyptianHieroglyphs
pub const EGYPTIAN_HIEROGLYPHS: &'static str = "EgyptianHieroglyphs";

/// The unicode block AnatolianHieroglyphs
pub const ANATOLIAN_HIEROGLYPHS: &'static str = "AnatolianHieroglyphs";

/// The unicode block BamumSupplement
pub const BAMUM_SUPPLEMENT: &'static str = "BamumSupplement";

/// The unicode block Mro
pub const MRO: &'static str = "Mro";

/// The unicode block BassaVah
pub const BASSA_VAH: &'static str = "BassaVah";

/// The unicode block PahawhHmong
pub const PAHAWH_HMONG: &'static str = "PahawhHmong";

/// The unicode block Miao
pub const MIAO: &'static str = "Miao";

/// The unicode block IdeographicSymbolsandPunctuation
pub const IDEOGRAPHIC_SYMBOLSAND_PUNCTUATION: &'static str = "IdeographicSymbolsandPunctuation";

/// The unicode block Tangut
pub const TANGUT: &'static str = "Tangut";

/// The unicode block TangutComponents
pub const TANGUT_COMPONENTS: &'static str = "TangutComponents";

/// The unicode block KanaSupplement
pub const KANA_SUPPLEMENT: &'static str = "KanaSupplement";

/// The unicode block KanaExtended-A
pub const KANA_EXTENDED_A: &'static str = "KanaExtended-A";

/// The unicode block Nushu
pub const NUSHU: &'static str = "Nushu";

/// The unicode block Duployan
pub const DUPLOYAN: &'static str = "Duployan";

/// The unicode block ShorthandFormatControls
pub const SHORTHAND_FORMAT_CONTROLS: &'static str = "ShorthandFormatControls";

/// The unicode block ByzantineMusicalSymbols
pub const BYZANTINE_MUSICAL_SYMBOLS: &'static str = "ByzantineMusicalSymbols";

/// The unicode block MusicalSymbols
pub const MUSICAL_SYMBOLS: &'static str = "MusicalSymbols";

/// The unicode block AncientGreekMusicalNotation
pub const ANCIENT_GREEK_MUSICAL_NOTATION: &'static str = "AncientGreekMusicalNotation";

/// The unicode block TaiXuanJingSymbols
pub const TAI_XUAN_JING_SYMBOLS: &'static str = "TaiXuanJingSymbols";

/// The unicode block CountingRodNumerals
pub const COUNTING_ROD_NUMERALS: &'static str = "CountingRodNumerals";

/// The unicode block MathematicalAlphanumericSymbols
pub const MATHEMATICAL_ALPHANUMERIC_SYMBOLS: &'static str = "MathematicalAlphanumericSymbols";

/// The unicode block SuttonSignWriting
pub const SUTTON_SIGN_WRITING: &'static str = "SuttonSignWriting";

/// The unicode block GlagoliticSupplement
pub const GLAGOLITIC_SUPPLEMENT: &'static str = "GlagoliticSupplement";

/// The unicode block MendeKikakui
pub const MENDE_KIKAKUI: &'static str = "MendeKikakui";

/// The unicode block Adlam
pub const ADLAM: &'static str = "Adlam";

/// The unicode block ArabicMathematicalAlphabeticSymbols
pub const ARABIC_MATHEMATICAL_ALPHABETIC_SYMBOLS: &'static str =
    "ArabicMathematicalAlphabeticSymbols";

/// The unicode block MahjongTiles
pub const MAHJONG_TILES: &'static str = "MahjongTiles";

/// The unicode block DominoTiles
pub const DOMINO_TILES: &'static str = "DominoTiles";

/// The unicode block PlayingCards
pub const PLAYING_CARDS: &'static str = "PlayingCards";

/// The unicode block EnclosedAlphanumericSupplement
pub const ENCLOSED_ALPHANUMERIC_SUPPLEMENT: &'static str = "EnclosedAlphanumericSupplement";

/// The unicode block EnclosedIdeographicSupplement
pub const ENCLOSED_IDEOGRAPHIC_SUPPLEMENT: &'static str = "EnclosedIdeographicSupplement";

/// The unicode block MiscellaneousSymbolsandPictographs
pub const MISCELLANEOUS_SYMBOLSAND_PICTOGRAPHS: &'static str = "MiscellaneousSymbolsandPictographs";

/// The unicode block Emoticons
pub const EMOTICONS: &'static str = "Emoticons";

/// The unicode block OrnamentalDingbats
pub const ORNAMENTAL_DINGBATS: &'static str = "OrnamentalDingbats";

/// The unicode block TransportandMapSymbols
pub const TRANSPORTAND_MAP_SYMBOLS: &'static str = "TransportandMapSymbols";

/// The unicode block AlchemicalSymbols
pub const ALCHEMICAL_SYMBOLS: &'static str = "AlchemicalSymbols";

/// The unicode block GeometricShapesExtended
pub const GEOMETRIC_SHAPES_EXTENDED: &'static str = "GeometricShapesExtended";

/// The unicode block SupplementalArrows-C
pub const SUPPLEMENTAL_ARROWS_C: &'static str = "SupplementalArrows-C";

/// The unicode block SupplementalSymbolsandPictographs
pub const SUPPLEMENTAL_SYMBOLSAND_PICTOGRAPHS: &'static str = "SupplementalSymbolsandPictographs";

/// The unicode block CJKUnifiedIdeographsExtensionB
pub const CJKUNIFIED_IDEOGRAPHS_EXTENSION_B: &'static str = "CJKUnifiedIdeographsExtensionB";

/// The unicode block CJKUnifiedIdeographsExtensionC
pub const CJKUNIFIED_IDEOGRAPHS_EXTENSION_C: &'static str = "CJKUnifiedIdeographsExtensionC";

/// The unicode block CJKUnifiedIdeographsExtensionD
pub const CJKUNIFIED_IDEOGRAPHS_EXTENSION_D: &'static str = "CJKUnifiedIdeographsExtensionD";

/// The unicode block CJKUnifiedIdeographsExtensionE
pub const CJKUNIFIED_IDEOGRAPHS_EXTENSION_E: &'static str = "CJKUnifiedIdeographsExtensionE";

/// The unicode block CJKUnifiedIdeographsExtensionF
pub const CJKUNIFIED_IDEOGRAPHS_EXTENSION_F: &'static str = "CJKUnifiedIdeographsExtensionF";

/// The unicode block CJKCompatibilityIdeographsSupplement
pub const CJKCOMPATIBILITY_IDEOGRAPHS_SUPPLEMENT: &'static str =
    "CJKCompatibilityIdeographsSupplement";

/// The unicode block Tags
pub const TAGS: &'static str = "Tags";

/// The unicode block VariationSelectorsSupplement
pub const VARIATION_SELECTORS_SUPPLEMENT: &'static str = "VariationSelectorsSupplement";

/// The unicode block SupplementaryPrivateUseArea-A
pub const SUPPLEMENTARY_PRIVATE_USE_AREA_A: &'static str = "SupplementaryPrivateUseArea-A";

/// The unicode block SupplementaryPrivateUseArea-B
pub const SUPPLEMENTARY_PRIVATE_USE_AREA_B: &'static str = "SupplementaryPrivateUseArea-B";

/// The database of Unicode blocks accessible by names
lazy_static! {
    static ref DATABASE: HashMap<&'static str, UnicodeBlock> = {
        let mut m = HashMap::new();
        m.insert(BASIC_LATIN, UnicodeBlock::new("BasicLatin".to_owned(), 0x0, 0x7F));
        m.insert(LATIN_1SUPPLEMENT, UnicodeBlock::new("Latin-1Supplement".to_owned(), 0x80, 0xFF));
        m.insert(LATIN_EXTENDED_A, UnicodeBlock::new("LatinExtended-A".to_owned(), 0x100, 0x17F));
        m.insert(LATIN_EXTENDED_B, UnicodeBlock::new("LatinExtended-B".to_owned(), 0x180, 0x24F));
        m.insert(IPAEXTENSIONS, UnicodeBlock::new("IPAExtensions".to_owned(), 0x250, 0x2AF));
        m.insert(SPACING_MODIFIER_LETTERS, UnicodeBlock::new("SpacingModifierLetters".to_owned(), 0x2B0, 0x2FF));
        m.insert(COMBINING_DIACRITICAL_MARKS, UnicodeBlock::new("CombiningDiacriticalMarks".to_owned(), 0x300, 0x36F));
        m.insert(GREEKAND_COPTIC, UnicodeBlock::new("GreekandCoptic".to_owned(), 0x370, 0x3FF));
        m.insert(CYRILLIC, UnicodeBlock::new("Cyrillic".to_owned(), 0x400, 0x4FF));
        m.insert(CYRILLIC_SUPPLEMENT, UnicodeBlock::new("CyrillicSupplement".to_owned(), 0x500, 0x52F));
        m.insert(ARMENIAN, UnicodeBlock::new("Armenian".to_owned(), 0x530, 0x58F));
        m.insert(HEBREW, UnicodeBlock::new("Hebrew".to_owned(), 0x590, 0x5FF));
        m.insert(ARABIC, UnicodeBlock::new("Arabic".to_owned(), 0x600, 0x6FF));
        m.insert(SYRIAC, UnicodeBlock::new("Syriac".to_owned(), 0x700, 0x74F));
        m.insert(ARABIC_SUPPLEMENT, UnicodeBlock::new("ArabicSupplement".to_owned(), 0x750, 0x77F));
        m.insert(THAANA, UnicodeBlock::new("Thaana".to_owned(), 0x780, 0x7BF));
        m.insert(NKO, UnicodeBlock::new("NKo".to_owned(), 0x7C0, 0x7FF));
        m.insert(SAMARITAN, UnicodeBlock::new("Samaritan".to_owned(), 0x800, 0x83F));
        m.insert(MANDAIC, UnicodeBlock::new("Mandaic".to_owned(), 0x840, 0x85F));
        m.insert(SYRIAC_SUPPLEMENT, UnicodeBlock::new("SyriacSupplement".to_owned(), 0x860, 0x86F));
        m.insert(ARABIC_EXTENDED_A, UnicodeBlock::new("ArabicExtended-A".to_owned(), 0x8A0, 0x8FF));
        m.insert(DEVANAGARI, UnicodeBlock::new("Devanagari".to_owned(), 0x900, 0x97F));
        m.insert(BENGALI, UnicodeBlock::new("Bengali".to_owned(), 0x980, 0x9FF));
        m.insert(GURMUKHI, UnicodeBlock::new("Gurmukhi".to_owned(), 0xA00, 0xA7F));
        m.insert(GUJARATI, UnicodeBlock::new("Gujarati".to_owned(), 0xA80, 0xAFF));
        m.insert(ORIYA, UnicodeBlock::new("Oriya".to_owned(), 0xB00, 0xB7F));
        m.insert(TAMIL, UnicodeBlock::new("Tamil".to_owned(), 0xB80, 0xBFF));
        m.insert(TELUGU, UnicodeBlock::new("Telugu".to_owned(), 0xC00, 0xC7F));
        m.insert(KANNADA, UnicodeBlock::new("Kannada".to_owned(), 0xC80, 0xCFF));
        m.insert(MALAYALAM, UnicodeBlock::new("Malayalam".to_owned(), 0xD00, 0xD7F));
        m.insert(SINHALA, UnicodeBlock::new("Sinhala".to_owned(), 0xD80, 0xDFF));
        m.insert(THAI, UnicodeBlock::new("Thai".to_owned(), 0xE00, 0xE7F));
        m.insert(LAO, UnicodeBlock::new("Lao".to_owned(), 0xE80, 0xEFF));
        m.insert(TIBETAN, UnicodeBlock::new("Tibetan".to_owned(), 0xF00, 0xFFF));
        m.insert(MYANMAR, UnicodeBlock::new("Myanmar".to_owned(), 0x1000, 0x109F));
        m.insert(GEORGIAN, UnicodeBlock::new("Georgian".to_owned(), 0x10A0, 0x10FF));
        m.insert(HANGUL_JAMO, UnicodeBlock::new("HangulJamo".to_owned(), 0x1100, 0x11FF));
        m.insert(ETHIOPIC, UnicodeBlock::new("Ethiopic".to_owned(), 0x1200, 0x137F));
        m.insert(ETHIOPIC_SUPPLEMENT, UnicodeBlock::new("EthiopicSupplement".to_owned(), 0x1380, 0x139F));
        m.insert(CHEROKEE, UnicodeBlock::new("Cherokee".to_owned(), 0x13A0, 0x13FF));
        m.insert(UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS, UnicodeBlock::new("UnifiedCanadianAboriginalSyllabics".to_owned(), 0x1400, 0x167F));
        m.insert(OGHAM, UnicodeBlock::new("Ogham".to_owned(), 0x1680, 0x169F));
        m.insert(RUNIC, UnicodeBlock::new("Runic".to_owned(), 0x16A0, 0x16FF));
        m.insert(TAGALOG, UnicodeBlock::new("Tagalog".to_owned(), 0x1700, 0x171F));
        m.insert(HANUNOO, UnicodeBlock::new("Hanunoo".to_owned(), 0x1720, 0x173F));
        m.insert(BUHID, UnicodeBlock::new("Buhid".to_owned(), 0x1740, 0x175F));
        m.insert(TAGBANWA, UnicodeBlock::new("Tagbanwa".to_owned(), 0x1760, 0x177F));
        m.insert(KHMER, UnicodeBlock::new("Khmer".to_owned(), 0x1780, 0x17FF));
        m.insert(MONGOLIAN, UnicodeBlock::new("Mongolian".to_owned(), 0x1800, 0x18AF));
        m.insert(UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS_EXTENDED, UnicodeBlock::new("UnifiedCanadianAboriginalSyllabicsExtended".to_owned(), 0x18B0, 0x18FF));
        m.insert(LIMBU, UnicodeBlock::new("Limbu".to_owned(), 0x1900, 0x194F));
        m.insert(TAI_LE, UnicodeBlock::new("TaiLe".to_owned(), 0x1950, 0x197F));
        m.insert(NEW_TAI_LUE, UnicodeBlock::new("NewTaiLue".to_owned(), 0x1980, 0x19DF));
        m.insert(KHMER_SYMBOLS, UnicodeBlock::new("KhmerSymbols".to_owned(), 0x19E0, 0x19FF));
        m.insert(BUGINESE, UnicodeBlock::new("Buginese".to_owned(), 0x1A00, 0x1A1F));
        m.insert(TAI_THAM, UnicodeBlock::new("TaiTham".to_owned(), 0x1A20, 0x1AAF));
        m.insert(COMBINING_DIACRITICAL_MARKS_EXTENDED, UnicodeBlock::new("CombiningDiacriticalMarksExtended".to_owned(), 0x1AB0, 0x1AFF));
        m.insert(BALINESE, UnicodeBlock::new("Balinese".to_owned(), 0x1B00, 0x1B7F));
        m.insert(SUNDANESE, UnicodeBlock::new("Sundanese".to_owned(), 0x1B80, 0x1BBF));
        m.insert(BATAK, UnicodeBlock::new("Batak".to_owned(), 0x1BC0, 0x1BFF));
        m.insert(LEPCHA, UnicodeBlock::new("Lepcha".to_owned(), 0x1C00, 0x1C4F));
        m.insert(OL_CHIKI, UnicodeBlock::new("OlChiki".to_owned(), 0x1C50, 0x1C7F));
        m.insert(CYRILLIC_EXTENDED_C, UnicodeBlock::new("CyrillicExtended-C".to_owned(), 0x1C80, 0x1C8F));
        m.insert(SUNDANESE_SUPPLEMENT, UnicodeBlock::new("SundaneseSupplement".to_owned(), 0x1CC0, 0x1CCF));
        m.insert(VEDIC_EXTENSIONS, UnicodeBlock::new("VedicExtensions".to_owned(), 0x1CD0, 0x1CFF));
        m.insert(PHONETIC_EXTENSIONS, UnicodeBlock::new("PhoneticExtensions".to_owned(), 0x1D00, 0x1D7F));
        m.insert(PHONETIC_EXTENSIONS_SUPPLEMENT, UnicodeBlock::new("PhoneticExtensionsSupplement".to_owned(), 0x1D80, 0x1DBF));
        m.insert(COMBINING_DIACRITICAL_MARKS_SUPPLEMENT, UnicodeBlock::new("CombiningDiacriticalMarksSupplement".to_owned(), 0x1DC0, 0x1DFF));
        m.insert(LATIN_EXTENDED_ADDITIONAL, UnicodeBlock::new("LatinExtendedAdditional".to_owned(), 0x1E00, 0x1EFF));
        m.insert(GREEK_EXTENDED, UnicodeBlock::new("GreekExtended".to_owned(), 0x1F00, 0x1FFF));
        m.insert(GENERAL_PUNCTUATION, UnicodeBlock::new("GeneralPunctuation".to_owned(), 0x2000, 0x206F));
        m.insert(SUPERSCRIPTSAND_SUBSCRIPTS, UnicodeBlock::new("SuperscriptsandSubscripts".to_owned(), 0x2070, 0x209F));
        m.insert(CURRENCY_SYMBOLS, UnicodeBlock::new("CurrencySymbols".to_owned(), 0x20A0, 0x20CF));
        m.insert(COMBINING_DIACRITICAL_MARKSFOR_SYMBOLS, UnicodeBlock::new("CombiningDiacriticalMarksforSymbols".to_owned(), 0x20D0, 0x20FF));
        m.insert(LETTERLIKE_SYMBOLS, UnicodeBlock::new("LetterlikeSymbols".to_owned(), 0x2100, 0x214F));
        m.insert(NUMBER_FORMS, UnicodeBlock::new("NumberForms".to_owned(), 0x2150, 0x218F));
        m.insert(ARROWS, UnicodeBlock::new("Arrows".to_owned(), 0x2190, 0x21FF));
        m.insert(MATHEMATICAL_OPERATORS, UnicodeBlock::new("MathematicalOperators".to_owned(), 0x2200, 0x22FF));
        m.insert(MISCELLANEOUS_TECHNICAL, UnicodeBlock::new("MiscellaneousTechnical".to_owned(), 0x2300, 0x23FF));
        m.insert(CONTROL_PICTURES, UnicodeBlock::new("ControlPictures".to_owned(), 0x2400, 0x243F));
        m.insert(OPTICAL_CHARACTER_RECOGNITION, UnicodeBlock::new("OpticalCharacterRecognition".to_owned(), 0x2440, 0x245F));
        m.insert(ENCLOSED_ALPHANUMERICS, UnicodeBlock::new("EnclosedAlphanumerics".to_owned(), 0x2460, 0x24FF));
        m.insert(BOX_DRAWING, UnicodeBlock::new("BoxDrawing".to_owned(), 0x2500, 0x257F));
        m.insert(BLOCK_ELEMENTS, UnicodeBlock::new("BlockElements".to_owned(), 0x2580, 0x259F));
        m.insert(GEOMETRIC_SHAPES, UnicodeBlock::new("GeometricShapes".to_owned(), 0x25A0, 0x25FF));
        m.insert(MISCELLANEOUS_SYMBOLS, UnicodeBlock::new("MiscellaneousSymbols".to_owned(), 0x2600, 0x26FF));
        m.insert(DINGBATS, UnicodeBlock::new("Dingbats".to_owned(), 0x2700, 0x27BF));
        m.insert(MISCELLANEOUS_MATHEMATICAL_SYMBOLS_A, UnicodeBlock::new("MiscellaneousMathematicalSymbols-A".to_owned(), 0x27C0, 0x27EF));
        m.insert(SUPPLEMENTAL_ARROWS_A, UnicodeBlock::new("SupplementalArrows-A".to_owned(), 0x27F0, 0x27FF));
        m.insert(BRAILLE_PATTERNS, UnicodeBlock::new("BraillePatterns".to_owned(), 0x2800, 0x28FF));
        m.insert(SUPPLEMENTAL_ARROWS_B, UnicodeBlock::new("SupplementalArrows-B".to_owned(), 0x2900, 0x297F));
        m.insert(MISCELLANEOUS_MATHEMATICAL_SYMBOLS_B, UnicodeBlock::new("MiscellaneousMathematicalSymbols-B".to_owned(), 0x2980, 0x29FF));
        m.insert(SUPPLEMENTAL_MATHEMATICAL_OPERATORS, UnicodeBlock::new("SupplementalMathematicalOperators".to_owned(), 0x2A00, 0x2AFF));
        m.insert(MISCELLANEOUS_SYMBOLSAND_ARROWS, UnicodeBlock::new("MiscellaneousSymbolsandArrows".to_owned(), 0x2B00, 0x2BFF));
        m.insert(GLAGOLITIC, UnicodeBlock::new("Glagolitic".to_owned(), 0x2C00, 0x2C5F));
        m.insert(LATIN_EXTENDED_C, UnicodeBlock::new("LatinExtended-C".to_owned(), 0x2C60, 0x2C7F));
        m.insert(COPTIC, UnicodeBlock::new("Coptic".to_owned(), 0x2C80, 0x2CFF));
        m.insert(GEORGIAN_SUPPLEMENT, UnicodeBlock::new("GeorgianSupplement".to_owned(), 0x2D00, 0x2D2F));
        m.insert(TIFINAGH, UnicodeBlock::new("Tifinagh".to_owned(), 0x2D30, 0x2D7F));
        m.insert(ETHIOPIC_EXTENDED, UnicodeBlock::new("EthiopicExtended".to_owned(), 0x2D80, 0x2DDF));
        m.insert(CYRILLIC_EXTENDED_A, UnicodeBlock::new("CyrillicExtended-A".to_owned(), 0x2DE0, 0x2DFF));
        m.insert(SUPPLEMENTAL_PUNCTUATION, UnicodeBlock::new("SupplementalPunctuation".to_owned(), 0x2E00, 0x2E7F));
        m.insert(CJKRADICALS_SUPPLEMENT, UnicodeBlock::new("CJKRadicalsSupplement".to_owned(), 0x2E80, 0x2EFF));
        m.insert(KANGXI_RADICALS, UnicodeBlock::new("KangxiRadicals".to_owned(), 0x2F00, 0x2FDF));
        m.insert(IDEOGRAPHIC_DESCRIPTION_CHARACTERS, UnicodeBlock::new("IdeographicDescriptionCharacters".to_owned(), 0x2FF0, 0x2FFF));
        m.insert(CJKSYMBOLSAND_PUNCTUATION, UnicodeBlock::new("CJKSymbolsandPunctuation".to_owned(), 0x3000, 0x303F));
        m.insert(HIRAGANA, UnicodeBlock::new("Hiragana".to_owned(), 0x3040, 0x309F));
        m.insert(KATAKANA, UnicodeBlock::new("Katakana".to_owned(), 0x30A0, 0x30FF));
        m.insert(BOPOMOFO, UnicodeBlock::new("Bopomofo".to_owned(), 0x3100, 0x312F));
        m.insert(HANGUL_COMPATIBILITY_JAMO, UnicodeBlock::new("HangulCompatibilityJamo".to_owned(), 0x3130, 0x318F));
        m.insert(KANBUN, UnicodeBlock::new("Kanbun".to_owned(), 0x3190, 0x319F));
        m.insert(BOPOMOFO_EXTENDED, UnicodeBlock::new("BopomofoExtended".to_owned(), 0x31A0, 0x31BF));
        m.insert(CJKSTROKES, UnicodeBlock::new("CJKStrokes".to_owned(), 0x31C0, 0x31EF));
        m.insert(KATAKANA_PHONETIC_EXTENSIONS, UnicodeBlock::new("KatakanaPhoneticExtensions".to_owned(), 0x31F0, 0x31FF));
        m.insert(ENCLOSED_CJKLETTERSAND_MONTHS, UnicodeBlock::new("EnclosedCJKLettersandMonths".to_owned(), 0x3200, 0x32FF));
        m.insert(CJKCOMPATIBILITY, UnicodeBlock::new("CJKCompatibility".to_owned(), 0x3300, 0x33FF));
        m.insert(CJKUNIFIED_IDEOGRAPHS_EXTENSION_A, UnicodeBlock::new("CJKUnifiedIdeographsExtensionA".to_owned(), 0x3400, 0x4DBF));
        m.insert(YIJING_HEXAGRAM_SYMBOLS, UnicodeBlock::new("YijingHexagramSymbols".to_owned(), 0x4DC0, 0x4DFF));
        m.insert(CJKUNIFIED_IDEOGRAPHS, UnicodeBlock::new("CJKUnifiedIdeographs".to_owned(), 0x4E00, 0x9FFF));
        m.insert(YI_SYLLABLES, UnicodeBlock::new("YiSyllables".to_owned(), 0xA000, 0xA48F));
        m.insert(YI_RADICALS, UnicodeBlock::new("YiRadicals".to_owned(), 0xA490, 0xA4CF));
        m.insert(LISU, UnicodeBlock::new("Lisu".to_owned(), 0xA4D0, 0xA4FF));
        m.insert(VAI, UnicodeBlock::new("Vai".to_owned(), 0xA500, 0xA63F));
        m.insert(CYRILLIC_EXTENDED_B, UnicodeBlock::new("CyrillicExtended-B".to_owned(), 0xA640, 0xA69F));
        m.insert(BAMUM, UnicodeBlock::new("Bamum".to_owned(), 0xA6A0, 0xA6FF));
        m.insert(MODIFIER_TONE_LETTERS, UnicodeBlock::new("ModifierToneLetters".to_owned(), 0xA700, 0xA71F));
        m.insert(LATIN_EXTENDED_D, UnicodeBlock::new("LatinExtended-D".to_owned(), 0xA720, 0xA7FF));
        m.insert(SYLOTI_NAGRI, UnicodeBlock::new("SylotiNagri".to_owned(), 0xA800, 0xA82F));
        m.insert(COMMON_INDIC_NUMBER_FORMS, UnicodeBlock::new("CommonIndicNumberForms".to_owned(), 0xA830, 0xA83F));
        m.insert(PHAGS_PA, UnicodeBlock::new("Phags-pa".to_owned(), 0xA840, 0xA87F));
        m.insert(SAURASHTRA, UnicodeBlock::new("Saurashtra".to_owned(), 0xA880, 0xA8DF));
        m.insert(DEVANAGARI_EXTENDED, UnicodeBlock::new("DevanagariExtended".to_owned(), 0xA8E0, 0xA8FF));
        m.insert(KAYAH_LI, UnicodeBlock::new("KayahLi".to_owned(), 0xA900, 0xA92F));
        m.insert(REJANG, UnicodeBlock::new("Rejang".to_owned(), 0xA930, 0xA95F));
        m.insert(HANGUL_JAMO_EXTENDED_A, UnicodeBlock::new("HangulJamoExtended-A".to_owned(), 0xA960, 0xA97F));
        m.insert(JAVANESE, UnicodeBlock::new("Javanese".to_owned(), 0xA980, 0xA9DF));
        m.insert(MYANMAR_EXTENDED_B, UnicodeBlock::new("MyanmarExtended-B".to_owned(), 0xA9E0, 0xA9FF));
        m.insert(CHAM, UnicodeBlock::new("Cham".to_owned(), 0xAA00, 0xAA5F));
        m.insert(MYANMAR_EXTENDED_A, UnicodeBlock::new("MyanmarExtended-A".to_owned(), 0xAA60, 0xAA7F));
        m.insert(TAI_VIET, UnicodeBlock::new("TaiViet".to_owned(), 0xAA80, 0xAADF));
        m.insert(MEETEI_MAYEK_EXTENSIONS, UnicodeBlock::new("MeeteiMayekExtensions".to_owned(), 0xAAE0, 0xAAFF));
        m.insert(ETHIOPIC_EXTENDED_A, UnicodeBlock::new("EthiopicExtended-A".to_owned(), 0xAB00, 0xAB2F));
        m.insert(LATIN_EXTENDED_E, UnicodeBlock::new("LatinExtended-E".to_owned(), 0xAB30, 0xAB6F));
        m.insert(CHEROKEE_SUPPLEMENT, UnicodeBlock::new("CherokeeSupplement".to_owned(), 0xAB70, 0xABBF));
        m.insert(MEETEI_MAYEK, UnicodeBlock::new("MeeteiMayek".to_owned(), 0xABC0, 0xABFF));
        m.insert(HANGUL_SYLLABLES, UnicodeBlock::new("HangulSyllables".to_owned(), 0xAC00, 0xD7AF));
        m.insert(HANGUL_JAMO_EXTENDED_B, UnicodeBlock::new("HangulJamoExtended-B".to_owned(), 0xD7B0, 0xD7FF));
        m.insert(PRIVATE_USE_AREA, UnicodeBlock::new("PrivateUseArea".to_owned(), 0xE000, 0xF8FF));
        m.insert(CJKCOMPATIBILITY_IDEOGRAPHS, UnicodeBlock::new("CJKCompatibilityIdeographs".to_owned(), 0xF900, 0xFAFF));
        m.insert(ALPHABETIC_PRESENTATION_FORMS, UnicodeBlock::new("AlphabeticPresentationForms".to_owned(), 0xFB00, 0xFB4F));
        m.insert(ARABIC_PRESENTATION_FORMS_A, UnicodeBlock::new("ArabicPresentationForms-A".to_owned(), 0xFB50, 0xFDFF));
        m.insert(VARIATION_SELECTORS, UnicodeBlock::new("VariationSelectors".to_owned(), 0xFE00, 0xFE0F));
        m.insert(VERTICAL_FORMS, UnicodeBlock::new("VerticalForms".to_owned(), 0xFE10, 0xFE1F));
        m.insert(COMBINING_HALF_MARKS, UnicodeBlock::new("CombiningHalfMarks".to_owned(), 0xFE20, 0xFE2F));
        m.insert(CJKCOMPATIBILITY_FORMS, UnicodeBlock::new("CJKCompatibilityForms".to_owned(), 0xFE30, 0xFE4F));
        m.insert(SMALL_FORM_VARIANTS, UnicodeBlock::new("SmallFormVariants".to_owned(), 0xFE50, 0xFE6F));
        m.insert(ARABIC_PRESENTATION_FORMS_B, UnicodeBlock::new("ArabicPresentationForms-B".to_owned(), 0xFE70, 0xFEFF));
        m.insert(HALFWIDTHAND_FULLWIDTH_FORMS, UnicodeBlock::new("HalfwidthandFullwidthForms".to_owned(), 0xFF00, 0xFFEF));
        m.insert(SPECIALS, UnicodeBlock::new("Specials".to_owned(), 0xFFF0, 0xFFFF));
        m.insert(LINEAR_BSYLLABARY, UnicodeBlock::new("LinearBSyllabary".to_owned(), 0x10000, 0x1007F));
        m.insert(LINEAR_BIDEOGRAMS, UnicodeBlock::new("LinearBIdeograms".to_owned(), 0x10080, 0x100FF));
        m.insert(AEGEAN_NUMBERS, UnicodeBlock::new("AegeanNumbers".to_owned(), 0x10100, 0x1013F));
        m.insert(ANCIENT_GREEK_NUMBERS, UnicodeBlock::new("AncientGreekNumbers".to_owned(), 0x10140, 0x1018F));
        m.insert(ANCIENT_SYMBOLS, UnicodeBlock::new("AncientSymbols".to_owned(), 0x10190, 0x101CF));
        m.insert(PHAISTOS_DISC, UnicodeBlock::new("PhaistosDisc".to_owned(), 0x101D0, 0x101FF));
        m.insert(LYCIAN, UnicodeBlock::new("Lycian".to_owned(), 0x10280, 0x1029F));
        m.insert(CARIAN, UnicodeBlock::new("Carian".to_owned(), 0x102A0, 0x102DF));
        m.insert(COPTIC_EPACT_NUMBERS, UnicodeBlock::new("CopticEpactNumbers".to_owned(), 0x102E0, 0x102FF));
        m.insert(OLD_ITALIC, UnicodeBlock::new("OldItalic".to_owned(), 0x10300, 0x1032F));
        m.insert(GOTHIC, UnicodeBlock::new("Gothic".to_owned(), 0x10330, 0x1034F));
        m.insert(OLD_PERMIC, UnicodeBlock::new("OldPermic".to_owned(), 0x10350, 0x1037F));
        m.insert(UGARITIC, UnicodeBlock::new("Ugaritic".to_owned(), 0x10380, 0x1039F));
        m.insert(OLD_PERSIAN, UnicodeBlock::new("OldPersian".to_owned(), 0x103A0, 0x103DF));
        m.insert(DESERET, UnicodeBlock::new("Deseret".to_owned(), 0x10400, 0x1044F));
        m.insert(SHAVIAN, UnicodeBlock::new("Shavian".to_owned(), 0x10450, 0x1047F));
        m.insert(OSMANYA, UnicodeBlock::new("Osmanya".to_owned(), 0x10480, 0x104AF));
        m.insert(OSAGE, UnicodeBlock::new("Osage".to_owned(), 0x104B0, 0x104FF));
        m.insert(ELBASAN, UnicodeBlock::new("Elbasan".to_owned(), 0x10500, 0x1052F));
        m.insert(CAUCASIAN_ALBANIAN, UnicodeBlock::new("CaucasianAlbanian".to_owned(), 0x10530, 0x1056F));
        m.insert(LINEAR_A, UnicodeBlock::new("LinearA".to_owned(), 0x10600, 0x1077F));
        m.insert(CYPRIOT_SYLLABARY, UnicodeBlock::new("CypriotSyllabary".to_owned(), 0x10800, 0x1083F));
        m.insert(IMPERIAL_ARAMAIC, UnicodeBlock::new("ImperialAramaic".to_owned(), 0x10840, 0x1085F));
        m.insert(PALMYRENE, UnicodeBlock::new("Palmyrene".to_owned(), 0x10860, 0x1087F));
        m.insert(NABATAEAN, UnicodeBlock::new("Nabataean".to_owned(), 0x10880, 0x108AF));
        m.insert(HATRAN, UnicodeBlock::new("Hatran".to_owned(), 0x108E0, 0x108FF));
        m.insert(PHOENICIAN, UnicodeBlock::new("Phoenician".to_owned(), 0x10900, 0x1091F));
        m.insert(LYDIAN, UnicodeBlock::new("Lydian".to_owned(), 0x10920, 0x1093F));
        m.insert(MEROITIC_HIEROGLYPHS, UnicodeBlock::new("MeroiticHieroglyphs".to_owned(), 0x10980, 0x1099F));
        m.insert(MEROITIC_CURSIVE, UnicodeBlock::new("MeroiticCursive".to_owned(), 0x109A0, 0x109FF));
        m.insert(KHAROSHTHI, UnicodeBlock::new("Kharoshthi".to_owned(), 0x10A00, 0x10A5F));
        m.insert(OLD_SOUTH_ARABIAN, UnicodeBlock::new("OldSouthArabian".to_owned(), 0x10A60, 0x10A7F));
        m.insert(OLD_NORTH_ARABIAN, UnicodeBlock::new("OldNorthArabian".to_owned(), 0x10A80, 0x10A9F));
        m.insert(MANICHAEAN, UnicodeBlock::new("Manichaean".to_owned(), 0x10AC0, 0x10AFF));
        m.insert(AVESTAN, UnicodeBlock::new("Avestan".to_owned(), 0x10B00, 0x10B3F));
        m.insert(INSCRIPTIONAL_PARTHIAN, UnicodeBlock::new("InscriptionalParthian".to_owned(), 0x10B40, 0x10B5F));
        m.insert(INSCRIPTIONAL_PAHLAVI, UnicodeBlock::new("InscriptionalPahlavi".to_owned(), 0x10B60, 0x10B7F));
        m.insert(PSALTER_PAHLAVI, UnicodeBlock::new("PsalterPahlavi".to_owned(), 0x10B80, 0x10BAF));
        m.insert(OLD_TURKIC, UnicodeBlock::new("OldTurkic".to_owned(), 0x10C00, 0x10C4F));
        m.insert(OLD_HUNGARIAN, UnicodeBlock::new("OldHungarian".to_owned(), 0x10C80, 0x10CFF));
        m.insert(RUMI_NUMERAL_SYMBOLS, UnicodeBlock::new("RumiNumeralSymbols".to_owned(), 0x10E60, 0x10E7F));
        m.insert(BRAHMI, UnicodeBlock::new("Brahmi".to_owned(), 0x11000, 0x1107F));
        m.insert(KAITHI, UnicodeBlock::new("Kaithi".to_owned(), 0x11080, 0x110CF));
        m.insert(SORA_SOMPENG, UnicodeBlock::new("SoraSompeng".to_owned(), 0x110D0, 0x110FF));
        m.insert(CHAKMA, UnicodeBlock::new("Chakma".to_owned(), 0x11100, 0x1114F));
        m.insert(MAHAJANI, UnicodeBlock::new("Mahajani".to_owned(), 0x11150, 0x1117F));
        m.insert(SHARADA, UnicodeBlock::new("Sharada".to_owned(), 0x11180, 0x111DF));
        m.insert(SINHALA_ARCHAIC_NUMBERS, UnicodeBlock::new("SinhalaArchaicNumbers".to_owned(), 0x111E0, 0x111FF));
        m.insert(KHOJKI, UnicodeBlock::new("Khojki".to_owned(), 0x11200, 0x1124F));
        m.insert(MULTANI, UnicodeBlock::new("Multani".to_owned(), 0x11280, 0x112AF));
        m.insert(KHUDAWADI, UnicodeBlock::new("Khudawadi".to_owned(), 0x112B0, 0x112FF));
        m.insert(GRANTHA, UnicodeBlock::new("Grantha".to_owned(), 0x11300, 0x1137F));
        m.insert(NEWA, UnicodeBlock::new("Newa".to_owned(), 0x11400, 0x1147F));
        m.insert(TIRHUTA, UnicodeBlock::new("Tirhuta".to_owned(), 0x11480, 0x114DF));
        m.insert(SIDDHAM, UnicodeBlock::new("Siddham".to_owned(), 0x11580, 0x115FF));
        m.insert(MODI, UnicodeBlock::new("Modi".to_owned(), 0x11600, 0x1165F));
        m.insert(MONGOLIAN_SUPPLEMENT, UnicodeBlock::new("MongolianSupplement".to_owned(), 0x11660, 0x1167F));
        m.insert(TAKRI, UnicodeBlock::new("Takri".to_owned(), 0x11680, 0x116CF));
        m.insert(AHOM, UnicodeBlock::new("Ahom".to_owned(), 0x11700, 0x1173F));
        m.insert(WARANG_CITI, UnicodeBlock::new("WarangCiti".to_owned(), 0x118A0, 0x118FF));
        m.insert(ZANABAZAR_SQUARE, UnicodeBlock::new("ZanabazarSquare".to_owned(), 0x11A00, 0x11A4F));
        m.insert(SOYOMBO, UnicodeBlock::new("Soyombo".to_owned(), 0x11A50, 0x11AAF));
        m.insert(PAU_CIN_HAU, UnicodeBlock::new("PauCinHau".to_owned(), 0x11AC0, 0x11AFF));
        m.insert(BHAIKSUKI, UnicodeBlock::new("Bhaiksuki".to_owned(), 0x11C00, 0x11C6F));
        m.insert(MARCHEN, UnicodeBlock::new("Marchen".to_owned(), 0x11C70, 0x11CBF));
        m.insert(MASARAM_GONDI, UnicodeBlock::new("MasaramGondi".to_owned(), 0x11D00, 0x11D5F));
        m.insert(CUNEIFORM, UnicodeBlock::new("Cuneiform".to_owned(), 0x12000, 0x123FF));
        m.insert(CUNEIFORM_NUMBERSAND_PUNCTUATION, UnicodeBlock::new("CuneiformNumbersandPunctuation".to_owned(), 0x12400, 0x1247F));
        m.insert(EARLY_DYNASTIC_CUNEIFORM, UnicodeBlock::new("EarlyDynasticCuneiform".to_owned(), 0x12480, 0x1254F));
        m.insert(EGYPTIAN_HIEROGLYPHS, UnicodeBlock::new("EgyptianHieroglyphs".to_owned(), 0x13000, 0x1342F));
        m.insert(ANATOLIAN_HIEROGLYPHS, UnicodeBlock::new("AnatolianHieroglyphs".to_owned(), 0x14400, 0x1467F));
        m.insert(BAMUM_SUPPLEMENT, UnicodeBlock::new("BamumSupplement".to_owned(), 0x16800, 0x16A3F));
        m.insert(MRO, UnicodeBlock::new("Mro".to_owned(), 0x16A40, 0x16A6F));
        m.insert(BASSA_VAH, UnicodeBlock::new("BassaVah".to_owned(), 0x16AD0, 0x16AFF));
        m.insert(PAHAWH_HMONG, UnicodeBlock::new("PahawhHmong".to_owned(), 0x16B00, 0x16B8F));
        m.insert(MIAO, UnicodeBlock::new("Miao".to_owned(), 0x16F00, 0x16F9F));
        m.insert(IDEOGRAPHIC_SYMBOLSAND_PUNCTUATION, UnicodeBlock::new("IdeographicSymbolsandPunctuation".to_owned(), 0x16FE0, 0x16FFF));
        m.insert(TANGUT, UnicodeBlock::new("Tangut".to_owned(), 0x17000, 0x187FF));
        m.insert(TANGUT_COMPONENTS, UnicodeBlock::new("TangutComponents".to_owned(), 0x18800, 0x18AFF));
        m.insert(KANA_SUPPLEMENT, UnicodeBlock::new("KanaSupplement".to_owned(), 0x1B000, 0x1B0FF));
        m.insert(KANA_EXTENDED_A, UnicodeBlock::new("KanaExtended-A".to_owned(), 0x1B100, 0x1B12F));
        m.insert(NUSHU, UnicodeBlock::new("Nushu".to_owned(), 0x1B170, 0x1B2FF));
        m.insert(DUPLOYAN, UnicodeBlock::new("Duployan".to_owned(), 0x1BC00, 0x1BC9F));
        m.insert(SHORTHAND_FORMAT_CONTROLS, UnicodeBlock::new("ShorthandFormatControls".to_owned(), 0x1BCA0, 0x1BCAF));
        m.insert(BYZANTINE_MUSICAL_SYMBOLS, UnicodeBlock::new("ByzantineMusicalSymbols".to_owned(), 0x1D000, 0x1D0FF));
        m.insert(MUSICAL_SYMBOLS, UnicodeBlock::new("MusicalSymbols".to_owned(), 0x1D100, 0x1D1FF));
        m.insert(ANCIENT_GREEK_MUSICAL_NOTATION, UnicodeBlock::new("AncientGreekMusicalNotation".to_owned(), 0x1D200, 0x1D24F));
        m.insert(TAI_XUAN_JING_SYMBOLS, UnicodeBlock::new("TaiXuanJingSymbols".to_owned(), 0x1D300, 0x1D35F));
        m.insert(COUNTING_ROD_NUMERALS, UnicodeBlock::new("CountingRodNumerals".to_owned(), 0x1D360, 0x1D37F));
        m.insert(MATHEMATICAL_ALPHANUMERIC_SYMBOLS, UnicodeBlock::new("MathematicalAlphanumericSymbols".to_owned(), 0x1D400, 0x1D7FF));
        m.insert(SUTTON_SIGN_WRITING, UnicodeBlock::new("SuttonSignWriting".to_owned(), 0x1D800, 0x1DAAF));
        m.insert(GLAGOLITIC_SUPPLEMENT, UnicodeBlock::new("GlagoliticSupplement".to_owned(), 0x1E000, 0x1E02F));
        m.insert(MENDE_KIKAKUI, UnicodeBlock::new("MendeKikakui".to_owned(), 0x1E800, 0x1E8DF));
        m.insert(ADLAM, UnicodeBlock::new("Adlam".to_owned(), 0x1E900, 0x1E95F));
        m.insert(ARABIC_MATHEMATICAL_ALPHABETIC_SYMBOLS, UnicodeBlock::new("ArabicMathematicalAlphabeticSymbols".to_owned(), 0x1EE00, 0x1EEFF));
        m.insert(MAHJONG_TILES, UnicodeBlock::new("MahjongTiles".to_owned(), 0x1F000, 0x1F02F));
        m.insert(DOMINO_TILES, UnicodeBlock::new("DominoTiles".to_owned(), 0x1F030, 0x1F09F));
        m.insert(PLAYING_CARDS, UnicodeBlock::new("PlayingCards".to_owned(), 0x1F0A0, 0x1F0FF));
        m.insert(ENCLOSED_ALPHANUMERIC_SUPPLEMENT, UnicodeBlock::new("EnclosedAlphanumericSupplement".to_owned(), 0x1F100, 0x1F1FF));
        m.insert(ENCLOSED_IDEOGRAPHIC_SUPPLEMENT, UnicodeBlock::new("EnclosedIdeographicSupplement".to_owned(), 0x1F200, 0x1F2FF));
        m.insert(MISCELLANEOUS_SYMBOLSAND_PICTOGRAPHS, UnicodeBlock::new("MiscellaneousSymbolsandPictographs".to_owned(), 0x1F300, 0x1F5FF));
        m.insert(EMOTICONS, UnicodeBlock::new("Emoticons".to_owned(), 0x1F600, 0x1F64F));
        m.insert(ORNAMENTAL_DINGBATS, UnicodeBlock::new("OrnamentalDingbats".to_owned(), 0x1F650, 0x1F67F));
        m.insert(TRANSPORTAND_MAP_SYMBOLS, UnicodeBlock::new("TransportandMapSymbols".to_owned(), 0x1F680, 0x1F6FF));
        m.insert(ALCHEMICAL_SYMBOLS, UnicodeBlock::new("AlchemicalSymbols".to_owned(), 0x1F700, 0x1F77F));
        m.insert(GEOMETRIC_SHAPES_EXTENDED, UnicodeBlock::new("GeometricShapesExtended".to_owned(), 0x1F780, 0x1F7FF));
        m.insert(SUPPLEMENTAL_ARROWS_C, UnicodeBlock::new("SupplementalArrows-C".to_owned(), 0x1F800, 0x1F8FF));
        m.insert(SUPPLEMENTAL_SYMBOLSAND_PICTOGRAPHS, UnicodeBlock::new("SupplementalSymbolsandPictographs".to_owned(), 0x1F900, 0x1F9FF));
        m.insert(CJKUNIFIED_IDEOGRAPHS_EXTENSION_B, UnicodeBlock::new("CJKUnifiedIdeographsExtensionB".to_owned(), 0x20000, 0x2A6DF));
        m.insert(CJKUNIFIED_IDEOGRAPHS_EXTENSION_C, UnicodeBlock::new("CJKUnifiedIdeographsExtensionC".to_owned(), 0x2A700, 0x2B73F));
        m.insert(CJKUNIFIED_IDEOGRAPHS_EXTENSION_D, UnicodeBlock::new("CJKUnifiedIdeographsExtensionD".to_owned(), 0x2B740, 0x2B81F));
        m.insert(CJKUNIFIED_IDEOGRAPHS_EXTENSION_E, UnicodeBlock::new("CJKUnifiedIdeographsExtensionE".to_owned(), 0x2B820, 0x2CEAF));
        m.insert(CJKUNIFIED_IDEOGRAPHS_EXTENSION_F, UnicodeBlock::new("CJKUnifiedIdeographsExtensionF".to_owned(), 0x2CEB0, 0x2EBEF));
        m.insert(CJKCOMPATIBILITY_IDEOGRAPHS_SUPPLEMENT, UnicodeBlock::new("CJKCompatibilityIdeographsSupplement".to_owned(), 0x2F800, 0x2FA1F));
        m.insert(TAGS, UnicodeBlock::new("Tags".to_owned(), 0xE0000, 0xE007F));
        m.insert(VARIATION_SELECTORS_SUPPLEMENT, UnicodeBlock::new("VariationSelectorsSupplement".to_owned(), 0xE0100, 0xE01EF));
        m.insert(SUPPLEMENTARY_PRIVATE_USE_AREA_A, UnicodeBlock::new("SupplementaryPrivateUseArea-A".to_owned(), 0xF0000, 0xFFFFF));
        m.insert(SUPPLEMENTARY_PRIVATE_USE_AREA_B, UnicodeBlock::new("SupplementaryPrivateUseArea-B".to_owned(), 0x100000, 0x10FFFF));
        m
    };
}

/// Retrieves the definition of a block
pub fn get_block(key: &str) -> Option<&UnicodeBlock> {
    DATABASE.get(key)
}
