using System.Collections.Generic;

namespace Hime.Parsers.CF.LR
{
    class ItemSetReductionsRNGLALR1 : ItemSetReductions
    {
        private List<ItemSetActionRNReduce> p_ActionReductions;

        public override ICollection<ItemSetActionReduce> Reductions
        {
            get
            {
                List<ItemSetActionReduce> Temp = new List<ItemSetActionReduce>();
                foreach (ItemSetActionRNReduce action in p_ActionReductions)
                    Temp.Add(action);
                return Temp;
            }
        }
        public override TerminalSet ExpectedTerminals
        {
            get
            {
                TerminalSet Set = new TerminalSet();
                foreach (ItemSetActionRNReduce Reduction in p_ActionReductions)
                    Set.Add(Reduction.Lookahead);
                return Set;
            }
        }

        public ItemSetReductionsRNGLALR1() : base()
        {
            p_ActionReductions = new List<ItemSetActionRNReduce>();
        }

        public override void Build(ItemSet Set)
        {
            // Build shift actions
            foreach (Symbol Next in Set.Children.Keys)
            {
                List<ItemSetAction> Actions = new List<ItemSetAction>();
                Actions.Add(new ItemSetActionShift(Next, Set.Children[Next]));
            }

            // Redutions dictionnary for the given set
            Dictionary<Terminal, ItemLALR1> Reductions = new Dictionary<Terminal, ItemLALR1>();
            // Construct reductions
            foreach (ItemLALR1 Item in Set.Items)
            {
                // Check for right nulled reduction
                if (Item.Action == ItemAction.Shift && !Item.BaseRule.Definition.GetChoiceAtIndex(Item.DotPosition).Firsts.Contains(TerminalEpsilon.Instance))
                    continue;
                bool rightnulled = (Item.DotPosition != Item.BaseRule.Definition.GetChoiceAtIndex(0).Length);
                foreach (Terminal Lookahead in Item.Lookaheads)
                {
                    // There is already a shift action for the lookahead => conflict
                    if (Set.Children.ContainsKey(Lookahead))
                    {
                        ItemSetReductionsLR1.HandleConflict_ShiftReduce(typeof(MethodRNGLALR1), p_Conflicts, Item, Set, Lookahead);
                        ItemSetActionRNReduce Reduction = new ItemSetActionRNReduce(Lookahead, Item.BaseRule, Item.DotPosition);
                        p_ActionReductions.Add(Reduction);
                    }
                    // There is already a reduction action for the lookahead => conflict
                    else if (Reductions.ContainsKey(Lookahead))
                    {
                        ItemSetReductionsLR1.HandleConflict_ReduceReduce(typeof(MethodRNGLALR1), p_Conflicts, Item, Reductions[Lookahead], Set, Lookahead);
                        ItemSetActionRNReduce Reduction = new ItemSetActionRNReduce(Lookahead, Item.BaseRule, Item.DotPosition);
                        p_ActionReductions.Add(Reduction);
                    }
                    else // No conflict
                    {
                        // hide conflicts generated by reducing using right-nulled rules
                        if (!rightnulled)
                            Reductions.Add(Lookahead, Item);
                        ItemSetActionRNReduce Reduction = new ItemSetActionRNReduce(Lookahead, Item.BaseRule, Item.DotPosition);
                        p_ActionReductions.Add(Reduction);
                    }
                }
            }
        }
    }
}
