/*
 * WARNING: this file has been generated by
 * Hime Parser Generator 0.6.0.0
 */

using System.Collections.Generic;
using Hime.Redist.Symbols;
using Hime.Redist.Lexer;
using Hime.Redist.Parsers;

namespace Hime.HimeCC.CL
{
    internal class CommandLineLexer : TextLexer
    {
        private static readonly TextLexerAutomaton automaton = TextLexerAutomaton.FindAutomaton(typeof(CommandLineLexer), "CommandLineLexer.bin");
        public static readonly Terminal[] terminals = {
            new Terminal(0x1, "ε"),
            new Terminal(0x2, "$"),
            new Terminal(0x8, "ARG_VALUE_NAME"),
            new Terminal(0x9, "ARG_VALUE_NUMBER"),
            new Terminal(0x3, "WHITE_SPACE"),
            new Terminal(0x4, "ARG_NAME_SHORT"),
            new Terminal(0x6, "ARG_VALUE_QUOTE"),
            new Terminal(0x5, "ARG_NAME_LONG") };
        public CommandLineLexer(string input) : base(automaton, terminals, 0x3, new System.IO.StringReader(input)) {}
        public CommandLineLexer(System.IO.TextReader input) : base(automaton, terminals, 0x3, input) {}
    }
}
