/*
 * WARNING: this file has been generated by
 * Hime Parser Generator 0.6.0.0
 */

using System.Collections.Generic;
using Hime.Redist.Symbols;
using Hime.Redist.Lexer;
using Hime.Redist.Parsers;

namespace Hime.HimeCC.CL
{
    internal class CommandLineParser : LRkParser
    {
        private static readonly LRkAutomaton automaton = LRkAutomaton.FindAutomaton(typeof(CommandLineParser), "CommandLineParser.bin");
        private static readonly Variable[] variables = {
            new Variable(0xA, "value"), 
            new Variable(0xB, "name"), 
            new Variable(0xC, "argument"), 
            new Variable(0xD, "values"), 
            new Variable(0xE, "arguments"), 
            new Variable(0xF, "line"), 
            new Variable(0x10, "_v7345D94"), 
            new Variable(0x11, "_v8EAB058"), 
            new Variable(0x12, "_vE5FF4AC"), 
            new Variable(0x13, "_Axiom_") };
        private static readonly Virtual[] virtuals = {
 };
        public CommandLineParser(CommandLineLexer lexer) : base (automaton, variables, virtuals, null, lexer) { }
    }
}
