/**********************************************************************
* Copyright (c) 2013 Laurent Wouters and others
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Lesser General Public License as
* published by the Free Software Foundation, either version 3
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Lesser General Public License for more details.
* 
* You should have received a copy of the GNU Lesser General
* Public License along with this program.
* If not, see <http://www.gnu.org/licenses/>.
* 
* Contributors:
*     Laurent Wouters - lwouters@xowl.org
**********************************************************************/

/*
 * WARNING: this file has been generated by
 * Hime Parser Generator 0.6.0.0
 */

using System.Collections.Generic;
using Hime.Redist;
using Hime.Redist.Parsers;

namespace Hime.HimeCC.CL
{
    internal class CommandLineParser : LRkParser
    {
        private static readonly LRkAutomaton automaton = LRkAutomaton.Find(typeof(CommandLineParser), "CommandLineParser.bin");
        private static readonly Symbol[] variables = {
            new Symbol(0x9, "value"), 
            new Symbol(0xA, "argument"), 
            new Symbol(0xB, "values"), 
            new Symbol(0xC, "arguments"), 
            new Symbol(0xD, "line"), 
            new Symbol(0xE, "_v0"), 
            new Symbol(0xF, "_v1"), 
            new Symbol(0x10, "_v2"), 
            new Symbol(0x11, "_Axiom_") };
        private static readonly Symbol[] virtuals = {
 };
        public CommandLineParser(CommandLineLexer lexer) : base (automaton, variables, virtuals, null, lexer) { }
    }
}
