/*******************************************************************************
 * Copyright (c) 2018 Association Cénotélie (cenotelie.fr)
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General
 * Public License along with this program.
 * If not, see <http://www.gnu.org/licenses/>.
 *
 ******************************************************************************/

/**
 * WARNING: this file has been generated by
 * Hime Parser Generator
 */

package fr.cenotelie.hime.sdk;

import java.util.HashMap;
import java.util.Map;

/**
 * Contains the supported Unicode blocks
 */
public class UnicodeBlocks {
    /**
     * The Unicode block BasicLatin
     */
    public static final UnicodeBlock BLOCK_BasicLatin = new UnicodeBlock("BasicLatin", 0x0000, 0x007f);
    /**
     * The Unicode block Latin-1Supplement
     */
    public static final UnicodeBlock BLOCK_Latin1Supplement = new UnicodeBlock("Latin-1Supplement", 0x0080, 0x00ff);
    /**
     * The Unicode block LatinExtended-A
     */
    public static final UnicodeBlock BLOCK_LatinExtendedA = new UnicodeBlock("LatinExtended-A", 0x0100, 0x017f);
    /**
     * The Unicode block LatinExtended-B
     */
    public static final UnicodeBlock BLOCK_LatinExtendedB = new UnicodeBlock("LatinExtended-B", 0x0180, 0x024f);
    /**
     * The Unicode block IPAExtensions
     */
    public static final UnicodeBlock BLOCK_IPAExtensions = new UnicodeBlock("IPAExtensions", 0x0250, 0x02af);
    /**
     * The Unicode block SpacingModifierLetters
     */
    public static final UnicodeBlock BLOCK_SpacingModifierLetters = new UnicodeBlock("SpacingModifierLetters", 0x02b0, 0x02ff);
    /**
     * The Unicode block CombiningDiacriticalMarks
     */
    public static final UnicodeBlock BLOCK_CombiningDiacriticalMarks = new UnicodeBlock("CombiningDiacriticalMarks", 0x0300, 0x036f);
    /**
     * The Unicode block GreekandCoptic
     */
    public static final UnicodeBlock BLOCK_GreekandCoptic = new UnicodeBlock("GreekandCoptic", 0x0370, 0x03ff);
    /**
     * The Unicode block Cyrillic
     */
    public static final UnicodeBlock BLOCK_Cyrillic = new UnicodeBlock("Cyrillic", 0x0400, 0x04ff);
    /**
     * The Unicode block CyrillicSupplement
     */
    public static final UnicodeBlock BLOCK_CyrillicSupplement = new UnicodeBlock("CyrillicSupplement", 0x0500, 0x052f);
    /**
     * The Unicode block Armenian
     */
    public static final UnicodeBlock BLOCK_Armenian = new UnicodeBlock("Armenian", 0x0530, 0x058f);
    /**
     * The Unicode block Hebrew
     */
    public static final UnicodeBlock BLOCK_Hebrew = new UnicodeBlock("Hebrew", 0x0590, 0x05ff);
    /**
     * The Unicode block Arabic
     */
    public static final UnicodeBlock BLOCK_Arabic = new UnicodeBlock("Arabic", 0x0600, 0x06ff);
    /**
     * The Unicode block Syriac
     */
    public static final UnicodeBlock BLOCK_Syriac = new UnicodeBlock("Syriac", 0x0700, 0x074f);
    /**
     * The Unicode block ArabicSupplement
     */
    public static final UnicodeBlock BLOCK_ArabicSupplement = new UnicodeBlock("ArabicSupplement", 0x0750, 0x077f);
    /**
     * The Unicode block Thaana
     */
    public static final UnicodeBlock BLOCK_Thaana = new UnicodeBlock("Thaana", 0x0780, 0x07bf);
    /**
     * The Unicode block NKo
     */
    public static final UnicodeBlock BLOCK_NKo = new UnicodeBlock("NKo", 0x07c0, 0x07ff);
    /**
     * The Unicode block Samaritan
     */
    public static final UnicodeBlock BLOCK_Samaritan = new UnicodeBlock("Samaritan", 0x0800, 0x083f);
    /**
     * The Unicode block Mandaic
     */
    public static final UnicodeBlock BLOCK_Mandaic = new UnicodeBlock("Mandaic", 0x0840, 0x085f);
    /**
     * The Unicode block SyriacSupplement
     */
    public static final UnicodeBlock BLOCK_SyriacSupplement = new UnicodeBlock("SyriacSupplement", 0x0860, 0x086f);
    /**
     * The Unicode block ArabicExtended-A
     */
    public static final UnicodeBlock BLOCK_ArabicExtendedA = new UnicodeBlock("ArabicExtended-A", 0x08a0, 0x08ff);
    /**
     * The Unicode block Devanagari
     */
    public static final UnicodeBlock BLOCK_Devanagari = new UnicodeBlock("Devanagari", 0x0900, 0x097f);
    /**
     * The Unicode block Bengali
     */
    public static final UnicodeBlock BLOCK_Bengali = new UnicodeBlock("Bengali", 0x0980, 0x09ff);
    /**
     * The Unicode block Gurmukhi
     */
    public static final UnicodeBlock BLOCK_Gurmukhi = new UnicodeBlock("Gurmukhi", 0x0a00, 0x0a7f);
    /**
     * The Unicode block Gujarati
     */
    public static final UnicodeBlock BLOCK_Gujarati = new UnicodeBlock("Gujarati", 0x0a80, 0x0aff);
    /**
     * The Unicode block Oriya
     */
    public static final UnicodeBlock BLOCK_Oriya = new UnicodeBlock("Oriya", 0x0b00, 0x0b7f);
    /**
     * The Unicode block Tamil
     */
    public static final UnicodeBlock BLOCK_Tamil = new UnicodeBlock("Tamil", 0x0b80, 0x0bff);
    /**
     * The Unicode block Telugu
     */
    public static final UnicodeBlock BLOCK_Telugu = new UnicodeBlock("Telugu", 0x0c00, 0x0c7f);
    /**
     * The Unicode block Kannada
     */
    public static final UnicodeBlock BLOCK_Kannada = new UnicodeBlock("Kannada", 0x0c80, 0x0cff);
    /**
     * The Unicode block Malayalam
     */
    public static final UnicodeBlock BLOCK_Malayalam = new UnicodeBlock("Malayalam", 0x0d00, 0x0d7f);
    /**
     * The Unicode block Sinhala
     */
    public static final UnicodeBlock BLOCK_Sinhala = new UnicodeBlock("Sinhala", 0x0d80, 0x0dff);
    /**
     * The Unicode block Thai
     */
    public static final UnicodeBlock BLOCK_Thai = new UnicodeBlock("Thai", 0x0e00, 0x0e7f);
    /**
     * The Unicode block Lao
     */
    public static final UnicodeBlock BLOCK_Lao = new UnicodeBlock("Lao", 0x0e80, 0x0eff);
    /**
     * The Unicode block Tibetan
     */
    public static final UnicodeBlock BLOCK_Tibetan = new UnicodeBlock("Tibetan", 0x0f00, 0x0fff);
    /**
     * The Unicode block Myanmar
     */
    public static final UnicodeBlock BLOCK_Myanmar = new UnicodeBlock("Myanmar", 0x1000, 0x109f);
    /**
     * The Unicode block Georgian
     */
    public static final UnicodeBlock BLOCK_Georgian = new UnicodeBlock("Georgian", 0x10a0, 0x10ff);
    /**
     * The Unicode block HangulJamo
     */
    public static final UnicodeBlock BLOCK_HangulJamo = new UnicodeBlock("HangulJamo", 0x1100, 0x11ff);
    /**
     * The Unicode block Ethiopic
     */
    public static final UnicodeBlock BLOCK_Ethiopic = new UnicodeBlock("Ethiopic", 0x1200, 0x137f);
    /**
     * The Unicode block EthiopicSupplement
     */
    public static final UnicodeBlock BLOCK_EthiopicSupplement = new UnicodeBlock("EthiopicSupplement", 0x1380, 0x139f);
    /**
     * The Unicode block Cherokee
     */
    public static final UnicodeBlock BLOCK_Cherokee = new UnicodeBlock("Cherokee", 0x13a0, 0x13ff);
    /**
     * The Unicode block UnifiedCanadianAboriginalSyllabics
     */
    public static final UnicodeBlock BLOCK_UnifiedCanadianAboriginalSyllabics = new UnicodeBlock("UnifiedCanadianAboriginalSyllabics", 0x1400, 0x167f);
    /**
     * The Unicode block Ogham
     */
    public static final UnicodeBlock BLOCK_Ogham = new UnicodeBlock("Ogham", 0x1680, 0x169f);
    /**
     * The Unicode block Runic
     */
    public static final UnicodeBlock BLOCK_Runic = new UnicodeBlock("Runic", 0x16a0, 0x16ff);
    /**
     * The Unicode block Tagalog
     */
    public static final UnicodeBlock BLOCK_Tagalog = new UnicodeBlock("Tagalog", 0x1700, 0x171f);
    /**
     * The Unicode block Hanunoo
     */
    public static final UnicodeBlock BLOCK_Hanunoo = new UnicodeBlock("Hanunoo", 0x1720, 0x173f);
    /**
     * The Unicode block Buhid
     */
    public static final UnicodeBlock BLOCK_Buhid = new UnicodeBlock("Buhid", 0x1740, 0x175f);
    /**
     * The Unicode block Tagbanwa
     */
    public static final UnicodeBlock BLOCK_Tagbanwa = new UnicodeBlock("Tagbanwa", 0x1760, 0x177f);
    /**
     * The Unicode block Khmer
     */
    public static final UnicodeBlock BLOCK_Khmer = new UnicodeBlock("Khmer", 0x1780, 0x17ff);
    /**
     * The Unicode block Mongolian
     */
    public static final UnicodeBlock BLOCK_Mongolian = new UnicodeBlock("Mongolian", 0x1800, 0x18af);
    /**
     * The Unicode block UnifiedCanadianAboriginalSyllabicsExtended
     */
    public static final UnicodeBlock BLOCK_UnifiedCanadianAboriginalSyllabicsExtended = new UnicodeBlock("UnifiedCanadianAboriginalSyllabicsExtended", 0x18b0, 0x18ff);
    /**
     * The Unicode block Limbu
     */
    public static final UnicodeBlock BLOCK_Limbu = new UnicodeBlock("Limbu", 0x1900, 0x194f);
    /**
     * The Unicode block TaiLe
     */
    public static final UnicodeBlock BLOCK_TaiLe = new UnicodeBlock("TaiLe", 0x1950, 0x197f);
    /**
     * The Unicode block NewTaiLue
     */
    public static final UnicodeBlock BLOCK_NewTaiLue = new UnicodeBlock("NewTaiLue", 0x1980, 0x19df);
    /**
     * The Unicode block KhmerSymbols
     */
    public static final UnicodeBlock BLOCK_KhmerSymbols = new UnicodeBlock("KhmerSymbols", 0x19e0, 0x19ff);
    /**
     * The Unicode block Buginese
     */
    public static final UnicodeBlock BLOCK_Buginese = new UnicodeBlock("Buginese", 0x1a00, 0x1a1f);
    /**
     * The Unicode block TaiTham
     */
    public static final UnicodeBlock BLOCK_TaiTham = new UnicodeBlock("TaiTham", 0x1a20, 0x1aaf);
    /**
     * The Unicode block CombiningDiacriticalMarksExtended
     */
    public static final UnicodeBlock BLOCK_CombiningDiacriticalMarksExtended = new UnicodeBlock("CombiningDiacriticalMarksExtended", 0x1ab0, 0x1aff);
    /**
     * The Unicode block Balinese
     */
    public static final UnicodeBlock BLOCK_Balinese = new UnicodeBlock("Balinese", 0x1b00, 0x1b7f);
    /**
     * The Unicode block Sundanese
     */
    public static final UnicodeBlock BLOCK_Sundanese = new UnicodeBlock("Sundanese", 0x1b80, 0x1bbf);
    /**
     * The Unicode block Batak
     */
    public static final UnicodeBlock BLOCK_Batak = new UnicodeBlock("Batak", 0x1bc0, 0x1bff);
    /**
     * The Unicode block Lepcha
     */
    public static final UnicodeBlock BLOCK_Lepcha = new UnicodeBlock("Lepcha", 0x1c00, 0x1c4f);
    /**
     * The Unicode block OlChiki
     */
    public static final UnicodeBlock BLOCK_OlChiki = new UnicodeBlock("OlChiki", 0x1c50, 0x1c7f);
    /**
     * The Unicode block CyrillicExtended-C
     */
    public static final UnicodeBlock BLOCK_CyrillicExtendedC = new UnicodeBlock("CyrillicExtended-C", 0x1c80, 0x1c8f);
    /**
     * The Unicode block SundaneseSupplement
     */
    public static final UnicodeBlock BLOCK_SundaneseSupplement = new UnicodeBlock("SundaneseSupplement", 0x1cc0, 0x1ccf);
    /**
     * The Unicode block VedicExtensions
     */
    public static final UnicodeBlock BLOCK_VedicExtensions = new UnicodeBlock("VedicExtensions", 0x1cd0, 0x1cff);
    /**
     * The Unicode block PhoneticExtensions
     */
    public static final UnicodeBlock BLOCK_PhoneticExtensions = new UnicodeBlock("PhoneticExtensions", 0x1d00, 0x1d7f);
    /**
     * The Unicode block PhoneticExtensionsSupplement
     */
    public static final UnicodeBlock BLOCK_PhoneticExtensionsSupplement = new UnicodeBlock("PhoneticExtensionsSupplement", 0x1d80, 0x1dbf);
    /**
     * The Unicode block CombiningDiacriticalMarksSupplement
     */
    public static final UnicodeBlock BLOCK_CombiningDiacriticalMarksSupplement = new UnicodeBlock("CombiningDiacriticalMarksSupplement", 0x1dc0, 0x1dff);
    /**
     * The Unicode block LatinExtendedAdditional
     */
    public static final UnicodeBlock BLOCK_LatinExtendedAdditional = new UnicodeBlock("LatinExtendedAdditional", 0x1e00, 0x1eff);
    /**
     * The Unicode block GreekExtended
     */
    public static final UnicodeBlock BLOCK_GreekExtended = new UnicodeBlock("GreekExtended", 0x1f00, 0x1fff);
    /**
     * The Unicode block GeneralPunctuation
     */
    public static final UnicodeBlock BLOCK_GeneralPunctuation = new UnicodeBlock("GeneralPunctuation", 0x2000, 0x206f);
    /**
     * The Unicode block SuperscriptsandSubscripts
     */
    public static final UnicodeBlock BLOCK_SuperscriptsandSubscripts = new UnicodeBlock("SuperscriptsandSubscripts", 0x2070, 0x209f);
    /**
     * The Unicode block CurrencySymbols
     */
    public static final UnicodeBlock BLOCK_CurrencySymbols = new UnicodeBlock("CurrencySymbols", 0x20a0, 0x20cf);
    /**
     * The Unicode block CombiningDiacriticalMarksforSymbols
     */
    public static final UnicodeBlock BLOCK_CombiningDiacriticalMarksforSymbols = new UnicodeBlock("CombiningDiacriticalMarksforSymbols", 0x20d0, 0x20ff);
    /**
     * The Unicode block LetterlikeSymbols
     */
    public static final UnicodeBlock BLOCK_LetterlikeSymbols = new UnicodeBlock("LetterlikeSymbols", 0x2100, 0x214f);
    /**
     * The Unicode block NumberForms
     */
    public static final UnicodeBlock BLOCK_NumberForms = new UnicodeBlock("NumberForms", 0x2150, 0x218f);
    /**
     * The Unicode block Arrows
     */
    public static final UnicodeBlock BLOCK_Arrows = new UnicodeBlock("Arrows", 0x2190, 0x21ff);
    /**
     * The Unicode block MathematicalOperators
     */
    public static final UnicodeBlock BLOCK_MathematicalOperators = new UnicodeBlock("MathematicalOperators", 0x2200, 0x22ff);
    /**
     * The Unicode block MiscellaneousTechnical
     */
    public static final UnicodeBlock BLOCK_MiscellaneousTechnical = new UnicodeBlock("MiscellaneousTechnical", 0x2300, 0x23ff);
    /**
     * The Unicode block ControlPictures
     */
    public static final UnicodeBlock BLOCK_ControlPictures = new UnicodeBlock("ControlPictures", 0x2400, 0x243f);
    /**
     * The Unicode block OpticalCharacterRecognition
     */
    public static final UnicodeBlock BLOCK_OpticalCharacterRecognition = new UnicodeBlock("OpticalCharacterRecognition", 0x2440, 0x245f);
    /**
     * The Unicode block EnclosedAlphanumerics
     */
    public static final UnicodeBlock BLOCK_EnclosedAlphanumerics = new UnicodeBlock("EnclosedAlphanumerics", 0x2460, 0x24ff);
    /**
     * The Unicode block BoxDrawing
     */
    public static final UnicodeBlock BLOCK_BoxDrawing = new UnicodeBlock("BoxDrawing", 0x2500, 0x257f);
    /**
     * The Unicode block BlockElements
     */
    public static final UnicodeBlock BLOCK_BlockElements = new UnicodeBlock("BlockElements", 0x2580, 0x259f);
    /**
     * The Unicode block GeometricShapes
     */
    public static final UnicodeBlock BLOCK_GeometricShapes = new UnicodeBlock("GeometricShapes", 0x25a0, 0x25ff);
    /**
     * The Unicode block MiscellaneousSymbols
     */
    public static final UnicodeBlock BLOCK_MiscellaneousSymbols = new UnicodeBlock("MiscellaneousSymbols", 0x2600, 0x26ff);
    /**
     * The Unicode block Dingbats
     */
    public static final UnicodeBlock BLOCK_Dingbats = new UnicodeBlock("Dingbats", 0x2700, 0x27bf);
    /**
     * The Unicode block MiscellaneousMathematicalSymbols-A
     */
    public static final UnicodeBlock BLOCK_MiscellaneousMathematicalSymbolsA = new UnicodeBlock("MiscellaneousMathematicalSymbols-A", 0x27c0, 0x27ef);
    /**
     * The Unicode block SupplementalArrows-A
     */
    public static final UnicodeBlock BLOCK_SupplementalArrowsA = new UnicodeBlock("SupplementalArrows-A", 0x27f0, 0x27ff);
    /**
     * The Unicode block BraillePatterns
     */
    public static final UnicodeBlock BLOCK_BraillePatterns = new UnicodeBlock("BraillePatterns", 0x2800, 0x28ff);
    /**
     * The Unicode block SupplementalArrows-B
     */
    public static final UnicodeBlock BLOCK_SupplementalArrowsB = new UnicodeBlock("SupplementalArrows-B", 0x2900, 0x297f);
    /**
     * The Unicode block MiscellaneousMathematicalSymbols-B
     */
    public static final UnicodeBlock BLOCK_MiscellaneousMathematicalSymbolsB = new UnicodeBlock("MiscellaneousMathematicalSymbols-B", 0x2980, 0x29ff);
    /**
     * The Unicode block SupplementalMathematicalOperators
     */
    public static final UnicodeBlock BLOCK_SupplementalMathematicalOperators = new UnicodeBlock("SupplementalMathematicalOperators", 0x2a00, 0x2aff);
    /**
     * The Unicode block MiscellaneousSymbolsandArrows
     */
    public static final UnicodeBlock BLOCK_MiscellaneousSymbolsandArrows = new UnicodeBlock("MiscellaneousSymbolsandArrows", 0x2b00, 0x2bff);
    /**
     * The Unicode block Glagolitic
     */
    public static final UnicodeBlock BLOCK_Glagolitic = new UnicodeBlock("Glagolitic", 0x2c00, 0x2c5f);
    /**
     * The Unicode block LatinExtended-C
     */
    public static final UnicodeBlock BLOCK_LatinExtendedC = new UnicodeBlock("LatinExtended-C", 0x2c60, 0x2c7f);
    /**
     * The Unicode block Coptic
     */
    public static final UnicodeBlock BLOCK_Coptic = new UnicodeBlock("Coptic", 0x2c80, 0x2cff);
    /**
     * The Unicode block GeorgianSupplement
     */
    public static final UnicodeBlock BLOCK_GeorgianSupplement = new UnicodeBlock("GeorgianSupplement", 0x2d00, 0x2d2f);
    /**
     * The Unicode block Tifinagh
     */
    public static final UnicodeBlock BLOCK_Tifinagh = new UnicodeBlock("Tifinagh", 0x2d30, 0x2d7f);
    /**
     * The Unicode block EthiopicExtended
     */
    public static final UnicodeBlock BLOCK_EthiopicExtended = new UnicodeBlock("EthiopicExtended", 0x2d80, 0x2ddf);
    /**
     * The Unicode block CyrillicExtended-A
     */
    public static final UnicodeBlock BLOCK_CyrillicExtendedA = new UnicodeBlock("CyrillicExtended-A", 0x2de0, 0x2dff);
    /**
     * The Unicode block SupplementalPunctuation
     */
    public static final UnicodeBlock BLOCK_SupplementalPunctuation = new UnicodeBlock("SupplementalPunctuation", 0x2e00, 0x2e7f);
    /**
     * The Unicode block CJKRadicalsSupplement
     */
    public static final UnicodeBlock BLOCK_CJKRadicalsSupplement = new UnicodeBlock("CJKRadicalsSupplement", 0x2e80, 0x2eff);
    /**
     * The Unicode block KangxiRadicals
     */
    public static final UnicodeBlock BLOCK_KangxiRadicals = new UnicodeBlock("KangxiRadicals", 0x2f00, 0x2fdf);
    /**
     * The Unicode block IdeographicDescriptionCharacters
     */
    public static final UnicodeBlock BLOCK_IdeographicDescriptionCharacters = new UnicodeBlock("IdeographicDescriptionCharacters", 0x2ff0, 0x2fff);
    /**
     * The Unicode block CJKSymbolsandPunctuation
     */
    public static final UnicodeBlock BLOCK_CJKSymbolsandPunctuation = new UnicodeBlock("CJKSymbolsandPunctuation", 0x3000, 0x303f);
    /**
     * The Unicode block Hiragana
     */
    public static final UnicodeBlock BLOCK_Hiragana = new UnicodeBlock("Hiragana", 0x3040, 0x309f);
    /**
     * The Unicode block Katakana
     */
    public static final UnicodeBlock BLOCK_Katakana = new UnicodeBlock("Katakana", 0x30a0, 0x30ff);
    /**
     * The Unicode block Bopomofo
     */
    public static final UnicodeBlock BLOCK_Bopomofo = new UnicodeBlock("Bopomofo", 0x3100, 0x312f);
    /**
     * The Unicode block HangulCompatibilityJamo
     */
    public static final UnicodeBlock BLOCK_HangulCompatibilityJamo = new UnicodeBlock("HangulCompatibilityJamo", 0x3130, 0x318f);
    /**
     * The Unicode block Kanbun
     */
    public static final UnicodeBlock BLOCK_Kanbun = new UnicodeBlock("Kanbun", 0x3190, 0x319f);
    /**
     * The Unicode block BopomofoExtended
     */
    public static final UnicodeBlock BLOCK_BopomofoExtended = new UnicodeBlock("BopomofoExtended", 0x31a0, 0x31bf);
    /**
     * The Unicode block CJKStrokes
     */
    public static final UnicodeBlock BLOCK_CJKStrokes = new UnicodeBlock("CJKStrokes", 0x31c0, 0x31ef);
    /**
     * The Unicode block KatakanaPhoneticExtensions
     */
    public static final UnicodeBlock BLOCK_KatakanaPhoneticExtensions = new UnicodeBlock("KatakanaPhoneticExtensions", 0x31f0, 0x31ff);
    /**
     * The Unicode block EnclosedCJKLettersandMonths
     */
    public static final UnicodeBlock BLOCK_EnclosedCJKLettersandMonths = new UnicodeBlock("EnclosedCJKLettersandMonths", 0x3200, 0x32ff);
    /**
     * The Unicode block CJKCompatibility
     */
    public static final UnicodeBlock BLOCK_CJKCompatibility = new UnicodeBlock("CJKCompatibility", 0x3300, 0x33ff);
    /**
     * The Unicode block CJKUnifiedIdeographsExtensionA
     */
    public static final UnicodeBlock BLOCK_CJKUnifiedIdeographsExtensionA = new UnicodeBlock("CJKUnifiedIdeographsExtensionA", 0x3400, 0x4dbf);
    /**
     * The Unicode block YijingHexagramSymbols
     */
    public static final UnicodeBlock BLOCK_YijingHexagramSymbols = new UnicodeBlock("YijingHexagramSymbols", 0x4dc0, 0x4dff);
    /**
     * The Unicode block CJKUnifiedIdeographs
     */
    public static final UnicodeBlock BLOCK_CJKUnifiedIdeographs = new UnicodeBlock("CJKUnifiedIdeographs", 0x4e00, 0x9fff);
    /**
     * The Unicode block YiSyllables
     */
    public static final UnicodeBlock BLOCK_YiSyllables = new UnicodeBlock("YiSyllables", 0xa000, 0xa48f);
    /**
     * The Unicode block YiRadicals
     */
    public static final UnicodeBlock BLOCK_YiRadicals = new UnicodeBlock("YiRadicals", 0xa490, 0xa4cf);
    /**
     * The Unicode block Lisu
     */
    public static final UnicodeBlock BLOCK_Lisu = new UnicodeBlock("Lisu", 0xa4d0, 0xa4ff);
    /**
     * The Unicode block Vai
     */
    public static final UnicodeBlock BLOCK_Vai = new UnicodeBlock("Vai", 0xa500, 0xa63f);
    /**
     * The Unicode block CyrillicExtended-B
     */
    public static final UnicodeBlock BLOCK_CyrillicExtendedB = new UnicodeBlock("CyrillicExtended-B", 0xa640, 0xa69f);
    /**
     * The Unicode block Bamum
     */
    public static final UnicodeBlock BLOCK_Bamum = new UnicodeBlock("Bamum", 0xa6a0, 0xa6ff);
    /**
     * The Unicode block ModifierToneLetters
     */
    public static final UnicodeBlock BLOCK_ModifierToneLetters = new UnicodeBlock("ModifierToneLetters", 0xa700, 0xa71f);
    /**
     * The Unicode block LatinExtended-D
     */
    public static final UnicodeBlock BLOCK_LatinExtendedD = new UnicodeBlock("LatinExtended-D", 0xa720, 0xa7ff);
    /**
     * The Unicode block SylotiNagri
     */
    public static final UnicodeBlock BLOCK_SylotiNagri = new UnicodeBlock("SylotiNagri", 0xa800, 0xa82f);
    /**
     * The Unicode block CommonIndicNumberForms
     */
    public static final UnicodeBlock BLOCK_CommonIndicNumberForms = new UnicodeBlock("CommonIndicNumberForms", 0xa830, 0xa83f);
    /**
     * The Unicode block Phags-pa
     */
    public static final UnicodeBlock BLOCK_Phagspa = new UnicodeBlock("Phags-pa", 0xa840, 0xa87f);
    /**
     * The Unicode block Saurashtra
     */
    public static final UnicodeBlock BLOCK_Saurashtra = new UnicodeBlock("Saurashtra", 0xa880, 0xa8df);
    /**
     * The Unicode block DevanagariExtended
     */
    public static final UnicodeBlock BLOCK_DevanagariExtended = new UnicodeBlock("DevanagariExtended", 0xa8e0, 0xa8ff);
    /**
     * The Unicode block KayahLi
     */
    public static final UnicodeBlock BLOCK_KayahLi = new UnicodeBlock("KayahLi", 0xa900, 0xa92f);
    /**
     * The Unicode block Rejang
     */
    public static final UnicodeBlock BLOCK_Rejang = new UnicodeBlock("Rejang", 0xa930, 0xa95f);
    /**
     * The Unicode block HangulJamoExtended-A
     */
    public static final UnicodeBlock BLOCK_HangulJamoExtendedA = new UnicodeBlock("HangulJamoExtended-A", 0xa960, 0xa97f);
    /**
     * The Unicode block Javanese
     */
    public static final UnicodeBlock BLOCK_Javanese = new UnicodeBlock("Javanese", 0xa980, 0xa9df);
    /**
     * The Unicode block MyanmarExtended-B
     */
    public static final UnicodeBlock BLOCK_MyanmarExtendedB = new UnicodeBlock("MyanmarExtended-B", 0xa9e0, 0xa9ff);
    /**
     * The Unicode block Cham
     */
    public static final UnicodeBlock BLOCK_Cham = new UnicodeBlock("Cham", 0xaa00, 0xaa5f);
    /**
     * The Unicode block MyanmarExtended-A
     */
    public static final UnicodeBlock BLOCK_MyanmarExtendedA = new UnicodeBlock("MyanmarExtended-A", 0xaa60, 0xaa7f);
    /**
     * The Unicode block TaiViet
     */
    public static final UnicodeBlock BLOCK_TaiViet = new UnicodeBlock("TaiViet", 0xaa80, 0xaadf);
    /**
     * The Unicode block MeeteiMayekExtensions
     */
    public static final UnicodeBlock BLOCK_MeeteiMayekExtensions = new UnicodeBlock("MeeteiMayekExtensions", 0xaae0, 0xaaff);
    /**
     * The Unicode block EthiopicExtended-A
     */
    public static final UnicodeBlock BLOCK_EthiopicExtendedA = new UnicodeBlock("EthiopicExtended-A", 0xab00, 0xab2f);
    /**
     * The Unicode block LatinExtended-E
     */
    public static final UnicodeBlock BLOCK_LatinExtendedE = new UnicodeBlock("LatinExtended-E", 0xab30, 0xab6f);
    /**
     * The Unicode block CherokeeSupplement
     */
    public static final UnicodeBlock BLOCK_CherokeeSupplement = new UnicodeBlock("CherokeeSupplement", 0xab70, 0xabbf);
    /**
     * The Unicode block MeeteiMayek
     */
    public static final UnicodeBlock BLOCK_MeeteiMayek = new UnicodeBlock("MeeteiMayek", 0xabc0, 0xabff);
    /**
     * The Unicode block HangulSyllables
     */
    public static final UnicodeBlock BLOCK_HangulSyllables = new UnicodeBlock("HangulSyllables", 0xac00, 0xd7af);
    /**
     * The Unicode block HangulJamoExtended-B
     */
    public static final UnicodeBlock BLOCK_HangulJamoExtendedB = new UnicodeBlock("HangulJamoExtended-B", 0xd7b0, 0xd7ff);
    /**
     * The Unicode block PrivateUseArea
     */
    public static final UnicodeBlock BLOCK_PrivateUseArea = new UnicodeBlock("PrivateUseArea", 0xe000, 0xf8ff);
    /**
     * The Unicode block CJKCompatibilityIdeographs
     */
    public static final UnicodeBlock BLOCK_CJKCompatibilityIdeographs = new UnicodeBlock("CJKCompatibilityIdeographs", 0xf900, 0xfaff);
    /**
     * The Unicode block AlphabeticPresentationForms
     */
    public static final UnicodeBlock BLOCK_AlphabeticPresentationForms = new UnicodeBlock("AlphabeticPresentationForms", 0xfb00, 0xfb4f);
    /**
     * The Unicode block ArabicPresentationForms-A
     */
    public static final UnicodeBlock BLOCK_ArabicPresentationFormsA = new UnicodeBlock("ArabicPresentationForms-A", 0xfb50, 0xfdff);
    /**
     * The Unicode block VariationSelectors
     */
    public static final UnicodeBlock BLOCK_VariationSelectors = new UnicodeBlock("VariationSelectors", 0xfe00, 0xfe0f);
    /**
     * The Unicode block VerticalForms
     */
    public static final UnicodeBlock BLOCK_VerticalForms = new UnicodeBlock("VerticalForms", 0xfe10, 0xfe1f);
    /**
     * The Unicode block CombiningHalfMarks
     */
    public static final UnicodeBlock BLOCK_CombiningHalfMarks = new UnicodeBlock("CombiningHalfMarks", 0xfe20, 0xfe2f);
    /**
     * The Unicode block CJKCompatibilityForms
     */
    public static final UnicodeBlock BLOCK_CJKCompatibilityForms = new UnicodeBlock("CJKCompatibilityForms", 0xfe30, 0xfe4f);
    /**
     * The Unicode block SmallFormVariants
     */
    public static final UnicodeBlock BLOCK_SmallFormVariants = new UnicodeBlock("SmallFormVariants", 0xfe50, 0xfe6f);
    /**
     * The Unicode block ArabicPresentationForms-B
     */
    public static final UnicodeBlock BLOCK_ArabicPresentationFormsB = new UnicodeBlock("ArabicPresentationForms-B", 0xfe70, 0xfeff);
    /**
     * The Unicode block HalfwidthandFullwidthForms
     */
    public static final UnicodeBlock BLOCK_HalfwidthandFullwidthForms = new UnicodeBlock("HalfwidthandFullwidthForms", 0xff00, 0xffef);
    /**
     * The Unicode block Specials
     */
    public static final UnicodeBlock BLOCK_Specials = new UnicodeBlock("Specials", 0xfff0, 0xffff);
    /**
     * The Unicode block LinearBSyllabary
     */
    public static final UnicodeBlock BLOCK_LinearBSyllabary = new UnicodeBlock("LinearBSyllabary", 0x00010000, 0x0001007f);
    /**
     * The Unicode block LinearBIdeograms
     */
    public static final UnicodeBlock BLOCK_LinearBIdeograms = new UnicodeBlock("LinearBIdeograms", 0x00010080, 0x000100ff);
    /**
     * The Unicode block AegeanNumbers
     */
    public static final UnicodeBlock BLOCK_AegeanNumbers = new UnicodeBlock("AegeanNumbers", 0x00010100, 0x0001013f);
    /**
     * The Unicode block AncientGreekNumbers
     */
    public static final UnicodeBlock BLOCK_AncientGreekNumbers = new UnicodeBlock("AncientGreekNumbers", 0x00010140, 0x0001018f);
    /**
     * The Unicode block AncientSymbols
     */
    public static final UnicodeBlock BLOCK_AncientSymbols = new UnicodeBlock("AncientSymbols", 0x00010190, 0x000101cf);
    /**
     * The Unicode block PhaistosDisc
     */
    public static final UnicodeBlock BLOCK_PhaistosDisc = new UnicodeBlock("PhaistosDisc", 0x000101d0, 0x000101ff);
    /**
     * The Unicode block Lycian
     */
    public static final UnicodeBlock BLOCK_Lycian = new UnicodeBlock("Lycian", 0x00010280, 0x0001029f);
    /**
     * The Unicode block Carian
     */
    public static final UnicodeBlock BLOCK_Carian = new UnicodeBlock("Carian", 0x000102a0, 0x000102df);
    /**
     * The Unicode block CopticEpactNumbers
     */
    public static final UnicodeBlock BLOCK_CopticEpactNumbers = new UnicodeBlock("CopticEpactNumbers", 0x000102e0, 0x000102ff);
    /**
     * The Unicode block OldItalic
     */
    public static final UnicodeBlock BLOCK_OldItalic = new UnicodeBlock("OldItalic", 0x00010300, 0x0001032f);
    /**
     * The Unicode block Gothic
     */
    public static final UnicodeBlock BLOCK_Gothic = new UnicodeBlock("Gothic", 0x00010330, 0x0001034f);
    /**
     * The Unicode block OldPermic
     */
    public static final UnicodeBlock BLOCK_OldPermic = new UnicodeBlock("OldPermic", 0x00010350, 0x0001037f);
    /**
     * The Unicode block Ugaritic
     */
    public static final UnicodeBlock BLOCK_Ugaritic = new UnicodeBlock("Ugaritic", 0x00010380, 0x0001039f);
    /**
     * The Unicode block OldPersian
     */
    public static final UnicodeBlock BLOCK_OldPersian = new UnicodeBlock("OldPersian", 0x000103a0, 0x000103df);
    /**
     * The Unicode block Deseret
     */
    public static final UnicodeBlock BLOCK_Deseret = new UnicodeBlock("Deseret", 0x00010400, 0x0001044f);
    /**
     * The Unicode block Shavian
     */
    public static final UnicodeBlock BLOCK_Shavian = new UnicodeBlock("Shavian", 0x00010450, 0x0001047f);
    /**
     * The Unicode block Osmanya
     */
    public static final UnicodeBlock BLOCK_Osmanya = new UnicodeBlock("Osmanya", 0x00010480, 0x000104af);
    /**
     * The Unicode block Osage
     */
    public static final UnicodeBlock BLOCK_Osage = new UnicodeBlock("Osage", 0x000104b0, 0x000104ff);
    /**
     * The Unicode block Elbasan
     */
    public static final UnicodeBlock BLOCK_Elbasan = new UnicodeBlock("Elbasan", 0x00010500, 0x0001052f);
    /**
     * The Unicode block CaucasianAlbanian
     */
    public static final UnicodeBlock BLOCK_CaucasianAlbanian = new UnicodeBlock("CaucasianAlbanian", 0x00010530, 0x0001056f);
    /**
     * The Unicode block LinearA
     */
    public static final UnicodeBlock BLOCK_LinearA = new UnicodeBlock("LinearA", 0x00010600, 0x0001077f);
    /**
     * The Unicode block CypriotSyllabary
     */
    public static final UnicodeBlock BLOCK_CypriotSyllabary = new UnicodeBlock("CypriotSyllabary", 0x00010800, 0x0001083f);
    /**
     * The Unicode block ImperialAramaic
     */
    public static final UnicodeBlock BLOCK_ImperialAramaic = new UnicodeBlock("ImperialAramaic", 0x00010840, 0x0001085f);
    /**
     * The Unicode block Palmyrene
     */
    public static final UnicodeBlock BLOCK_Palmyrene = new UnicodeBlock("Palmyrene", 0x00010860, 0x0001087f);
    /**
     * The Unicode block Nabataean
     */
    public static final UnicodeBlock BLOCK_Nabataean = new UnicodeBlock("Nabataean", 0x00010880, 0x000108af);
    /**
     * The Unicode block Hatran
     */
    public static final UnicodeBlock BLOCK_Hatran = new UnicodeBlock("Hatran", 0x000108e0, 0x000108ff);
    /**
     * The Unicode block Phoenician
     */
    public static final UnicodeBlock BLOCK_Phoenician = new UnicodeBlock("Phoenician", 0x00010900, 0x0001091f);
    /**
     * The Unicode block Lydian
     */
    public static final UnicodeBlock BLOCK_Lydian = new UnicodeBlock("Lydian", 0x00010920, 0x0001093f);
    /**
     * The Unicode block MeroiticHieroglyphs
     */
    public static final UnicodeBlock BLOCK_MeroiticHieroglyphs = new UnicodeBlock("MeroiticHieroglyphs", 0x00010980, 0x0001099f);
    /**
     * The Unicode block MeroiticCursive
     */
    public static final UnicodeBlock BLOCK_MeroiticCursive = new UnicodeBlock("MeroiticCursive", 0x000109a0, 0x000109ff);
    /**
     * The Unicode block Kharoshthi
     */
    public static final UnicodeBlock BLOCK_Kharoshthi = new UnicodeBlock("Kharoshthi", 0x00010a00, 0x00010a5f);
    /**
     * The Unicode block OldSouthArabian
     */
    public static final UnicodeBlock BLOCK_OldSouthArabian = new UnicodeBlock("OldSouthArabian", 0x00010a60, 0x00010a7f);
    /**
     * The Unicode block OldNorthArabian
     */
    public static final UnicodeBlock BLOCK_OldNorthArabian = new UnicodeBlock("OldNorthArabian", 0x00010a80, 0x00010a9f);
    /**
     * The Unicode block Manichaean
     */
    public static final UnicodeBlock BLOCK_Manichaean = new UnicodeBlock("Manichaean", 0x00010ac0, 0x00010aff);
    /**
     * The Unicode block Avestan
     */
    public static final UnicodeBlock BLOCK_Avestan = new UnicodeBlock("Avestan", 0x00010b00, 0x00010b3f);
    /**
     * The Unicode block InscriptionalParthian
     */
    public static final UnicodeBlock BLOCK_InscriptionalParthian = new UnicodeBlock("InscriptionalParthian", 0x00010b40, 0x00010b5f);
    /**
     * The Unicode block InscriptionalPahlavi
     */
    public static final UnicodeBlock BLOCK_InscriptionalPahlavi = new UnicodeBlock("InscriptionalPahlavi", 0x00010b60, 0x00010b7f);
    /**
     * The Unicode block PsalterPahlavi
     */
    public static final UnicodeBlock BLOCK_PsalterPahlavi = new UnicodeBlock("PsalterPahlavi", 0x00010b80, 0x00010baf);
    /**
     * The Unicode block OldTurkic
     */
    public static final UnicodeBlock BLOCK_OldTurkic = new UnicodeBlock("OldTurkic", 0x00010c00, 0x00010c4f);
    /**
     * The Unicode block OldHungarian
     */
    public static final UnicodeBlock BLOCK_OldHungarian = new UnicodeBlock("OldHungarian", 0x00010c80, 0x00010cff);
    /**
     * The Unicode block RumiNumeralSymbols
     */
    public static final UnicodeBlock BLOCK_RumiNumeralSymbols = new UnicodeBlock("RumiNumeralSymbols", 0x00010e60, 0x00010e7f);
    /**
     * The Unicode block Brahmi
     */
    public static final UnicodeBlock BLOCK_Brahmi = new UnicodeBlock("Brahmi", 0x00011000, 0x0001107f);
    /**
     * The Unicode block Kaithi
     */
    public static final UnicodeBlock BLOCK_Kaithi = new UnicodeBlock("Kaithi", 0x00011080, 0x000110cf);
    /**
     * The Unicode block SoraSompeng
     */
    public static final UnicodeBlock BLOCK_SoraSompeng = new UnicodeBlock("SoraSompeng", 0x000110d0, 0x000110ff);
    /**
     * The Unicode block Chakma
     */
    public static final UnicodeBlock BLOCK_Chakma = new UnicodeBlock("Chakma", 0x00011100, 0x0001114f);
    /**
     * The Unicode block Mahajani
     */
    public static final UnicodeBlock BLOCK_Mahajani = new UnicodeBlock("Mahajani", 0x00011150, 0x0001117f);
    /**
     * The Unicode block Sharada
     */
    public static final UnicodeBlock BLOCK_Sharada = new UnicodeBlock("Sharada", 0x00011180, 0x000111df);
    /**
     * The Unicode block SinhalaArchaicNumbers
     */
    public static final UnicodeBlock BLOCK_SinhalaArchaicNumbers = new UnicodeBlock("SinhalaArchaicNumbers", 0x000111e0, 0x000111ff);
    /**
     * The Unicode block Khojki
     */
    public static final UnicodeBlock BLOCK_Khojki = new UnicodeBlock("Khojki", 0x00011200, 0x0001124f);
    /**
     * The Unicode block Multani
     */
    public static final UnicodeBlock BLOCK_Multani = new UnicodeBlock("Multani", 0x00011280, 0x000112af);
    /**
     * The Unicode block Khudawadi
     */
    public static final UnicodeBlock BLOCK_Khudawadi = new UnicodeBlock("Khudawadi", 0x000112b0, 0x000112ff);
    /**
     * The Unicode block Grantha
     */
    public static final UnicodeBlock BLOCK_Grantha = new UnicodeBlock("Grantha", 0x00011300, 0x0001137f);
    /**
     * The Unicode block Newa
     */
    public static final UnicodeBlock BLOCK_Newa = new UnicodeBlock("Newa", 0x00011400, 0x0001147f);
    /**
     * The Unicode block Tirhuta
     */
    public static final UnicodeBlock BLOCK_Tirhuta = new UnicodeBlock("Tirhuta", 0x00011480, 0x000114df);
    /**
     * The Unicode block Siddham
     */
    public static final UnicodeBlock BLOCK_Siddham = new UnicodeBlock("Siddham", 0x00011580, 0x000115ff);
    /**
     * The Unicode block Modi
     */
    public static final UnicodeBlock BLOCK_Modi = new UnicodeBlock("Modi", 0x00011600, 0x0001165f);
    /**
     * The Unicode block MongolianSupplement
     */
    public static final UnicodeBlock BLOCK_MongolianSupplement = new UnicodeBlock("MongolianSupplement", 0x00011660, 0x0001167f);
    /**
     * The Unicode block Takri
     */
    public static final UnicodeBlock BLOCK_Takri = new UnicodeBlock("Takri", 0x00011680, 0x000116cf);
    /**
     * The Unicode block Ahom
     */
    public static final UnicodeBlock BLOCK_Ahom = new UnicodeBlock("Ahom", 0x00011700, 0x0001173f);
    /**
     * The Unicode block WarangCiti
     */
    public static final UnicodeBlock BLOCK_WarangCiti = new UnicodeBlock("WarangCiti", 0x000118a0, 0x000118ff);
    /**
     * The Unicode block ZanabazarSquare
     */
    public static final UnicodeBlock BLOCK_ZanabazarSquare = new UnicodeBlock("ZanabazarSquare", 0x00011a00, 0x00011a4f);
    /**
     * The Unicode block Soyombo
     */
    public static final UnicodeBlock BLOCK_Soyombo = new UnicodeBlock("Soyombo", 0x00011a50, 0x00011aaf);
    /**
     * The Unicode block PauCinHau
     */
    public static final UnicodeBlock BLOCK_PauCinHau = new UnicodeBlock("PauCinHau", 0x00011ac0, 0x00011aff);
    /**
     * The Unicode block Bhaiksuki
     */
    public static final UnicodeBlock BLOCK_Bhaiksuki = new UnicodeBlock("Bhaiksuki", 0x00011c00, 0x00011c6f);
    /**
     * The Unicode block Marchen
     */
    public static final UnicodeBlock BLOCK_Marchen = new UnicodeBlock("Marchen", 0x00011c70, 0x00011cbf);
    /**
     * The Unicode block MasaramGondi
     */
    public static final UnicodeBlock BLOCK_MasaramGondi = new UnicodeBlock("MasaramGondi", 0x00011d00, 0x00011d5f);
    /**
     * The Unicode block Cuneiform
     */
    public static final UnicodeBlock BLOCK_Cuneiform = new UnicodeBlock("Cuneiform", 0x00012000, 0x000123ff);
    /**
     * The Unicode block CuneiformNumbersandPunctuation
     */
    public static final UnicodeBlock BLOCK_CuneiformNumbersandPunctuation = new UnicodeBlock("CuneiformNumbersandPunctuation", 0x00012400, 0x0001247f);
    /**
     * The Unicode block EarlyDynasticCuneiform
     */
    public static final UnicodeBlock BLOCK_EarlyDynasticCuneiform = new UnicodeBlock("EarlyDynasticCuneiform", 0x00012480, 0x0001254f);
    /**
     * The Unicode block EgyptianHieroglyphs
     */
    public static final UnicodeBlock BLOCK_EgyptianHieroglyphs = new UnicodeBlock("EgyptianHieroglyphs", 0x00013000, 0x0001342f);
    /**
     * The Unicode block AnatolianHieroglyphs
     */
    public static final UnicodeBlock BLOCK_AnatolianHieroglyphs = new UnicodeBlock("AnatolianHieroglyphs", 0x00014400, 0x0001467f);
    /**
     * The Unicode block BamumSupplement
     */
    public static final UnicodeBlock BLOCK_BamumSupplement = new UnicodeBlock("BamumSupplement", 0x00016800, 0x00016a3f);
    /**
     * The Unicode block Mro
     */
    public static final UnicodeBlock BLOCK_Mro = new UnicodeBlock("Mro", 0x00016a40, 0x00016a6f);
    /**
     * The Unicode block BassaVah
     */
    public static final UnicodeBlock BLOCK_BassaVah = new UnicodeBlock("BassaVah", 0x00016ad0, 0x00016aff);
    /**
     * The Unicode block PahawhHmong
     */
    public static final UnicodeBlock BLOCK_PahawhHmong = new UnicodeBlock("PahawhHmong", 0x00016b00, 0x00016b8f);
    /**
     * The Unicode block Miao
     */
    public static final UnicodeBlock BLOCK_Miao = new UnicodeBlock("Miao", 0x00016f00, 0x00016f9f);
    /**
     * The Unicode block IdeographicSymbolsandPunctuation
     */
    public static final UnicodeBlock BLOCK_IdeographicSymbolsandPunctuation = new UnicodeBlock("IdeographicSymbolsandPunctuation", 0x00016fe0, 0x00016fff);
    /**
     * The Unicode block Tangut
     */
    public static final UnicodeBlock BLOCK_Tangut = new UnicodeBlock("Tangut", 0x00017000, 0x000187ff);
    /**
     * The Unicode block TangutComponents
     */
    public static final UnicodeBlock BLOCK_TangutComponents = new UnicodeBlock("TangutComponents", 0x00018800, 0x00018aff);
    /**
     * The Unicode block KanaSupplement
     */
    public static final UnicodeBlock BLOCK_KanaSupplement = new UnicodeBlock("KanaSupplement", 0x0001b000, 0x0001b0ff);
    /**
     * The Unicode block KanaExtended-A
     */
    public static final UnicodeBlock BLOCK_KanaExtendedA = new UnicodeBlock("KanaExtended-A", 0x0001b100, 0x0001b12f);
    /**
     * The Unicode block Nushu
     */
    public static final UnicodeBlock BLOCK_Nushu = new UnicodeBlock("Nushu", 0x0001b170, 0x0001b2ff);
    /**
     * The Unicode block Duployan
     */
    public static final UnicodeBlock BLOCK_Duployan = new UnicodeBlock("Duployan", 0x0001bc00, 0x0001bc9f);
    /**
     * The Unicode block ShorthandFormatControls
     */
    public static final UnicodeBlock BLOCK_ShorthandFormatControls = new UnicodeBlock("ShorthandFormatControls", 0x0001bca0, 0x0001bcaf);
    /**
     * The Unicode block ByzantineMusicalSymbols
     */
    public static final UnicodeBlock BLOCK_ByzantineMusicalSymbols = new UnicodeBlock("ByzantineMusicalSymbols", 0x0001d000, 0x0001d0ff);
    /**
     * The Unicode block MusicalSymbols
     */
    public static final UnicodeBlock BLOCK_MusicalSymbols = new UnicodeBlock("MusicalSymbols", 0x0001d100, 0x0001d1ff);
    /**
     * The Unicode block AncientGreekMusicalNotation
     */
    public static final UnicodeBlock BLOCK_AncientGreekMusicalNotation = new UnicodeBlock("AncientGreekMusicalNotation", 0x0001d200, 0x0001d24f);
    /**
     * The Unicode block TaiXuanJingSymbols
     */
    public static final UnicodeBlock BLOCK_TaiXuanJingSymbols = new UnicodeBlock("TaiXuanJingSymbols", 0x0001d300, 0x0001d35f);
    /**
     * The Unicode block CountingRodNumerals
     */
    public static final UnicodeBlock BLOCK_CountingRodNumerals = new UnicodeBlock("CountingRodNumerals", 0x0001d360, 0x0001d37f);
    /**
     * The Unicode block MathematicalAlphanumericSymbols
     */
    public static final UnicodeBlock BLOCK_MathematicalAlphanumericSymbols = new UnicodeBlock("MathematicalAlphanumericSymbols", 0x0001d400, 0x0001d7ff);
    /**
     * The Unicode block SuttonSignWriting
     */
    public static final UnicodeBlock BLOCK_SuttonSignWriting = new UnicodeBlock("SuttonSignWriting", 0x0001d800, 0x0001daaf);
    /**
     * The Unicode block GlagoliticSupplement
     */
    public static final UnicodeBlock BLOCK_GlagoliticSupplement = new UnicodeBlock("GlagoliticSupplement", 0x0001e000, 0x0001e02f);
    /**
     * The Unicode block MendeKikakui
     */
    public static final UnicodeBlock BLOCK_MendeKikakui = new UnicodeBlock("MendeKikakui", 0x0001e800, 0x0001e8df);
    /**
     * The Unicode block Adlam
     */
    public static final UnicodeBlock BLOCK_Adlam = new UnicodeBlock("Adlam", 0x0001e900, 0x0001e95f);
    /**
     * The Unicode block ArabicMathematicalAlphabeticSymbols
     */
    public static final UnicodeBlock BLOCK_ArabicMathematicalAlphabeticSymbols = new UnicodeBlock("ArabicMathematicalAlphabeticSymbols", 0x0001ee00, 0x0001eeff);
    /**
     * The Unicode block MahjongTiles
     */
    public static final UnicodeBlock BLOCK_MahjongTiles = new UnicodeBlock("MahjongTiles", 0x0001f000, 0x0001f02f);
    /**
     * The Unicode block DominoTiles
     */
    public static final UnicodeBlock BLOCK_DominoTiles = new UnicodeBlock("DominoTiles", 0x0001f030, 0x0001f09f);
    /**
     * The Unicode block PlayingCards
     */
    public static final UnicodeBlock BLOCK_PlayingCards = new UnicodeBlock("PlayingCards", 0x0001f0a0, 0x0001f0ff);
    /**
     * The Unicode block EnclosedAlphanumericSupplement
     */
    public static final UnicodeBlock BLOCK_EnclosedAlphanumericSupplement = new UnicodeBlock("EnclosedAlphanumericSupplement", 0x0001f100, 0x0001f1ff);
    /**
     * The Unicode block EnclosedIdeographicSupplement
     */
    public static final UnicodeBlock BLOCK_EnclosedIdeographicSupplement = new UnicodeBlock("EnclosedIdeographicSupplement", 0x0001f200, 0x0001f2ff);
    /**
     * The Unicode block MiscellaneousSymbolsandPictographs
     */
    public static final UnicodeBlock BLOCK_MiscellaneousSymbolsandPictographs = new UnicodeBlock("MiscellaneousSymbolsandPictographs", 0x0001f300, 0x0001f5ff);
    /**
     * The Unicode block Emoticons
     */
    public static final UnicodeBlock BLOCK_Emoticons = new UnicodeBlock("Emoticons", 0x0001f600, 0x0001f64f);
    /**
     * The Unicode block OrnamentalDingbats
     */
    public static final UnicodeBlock BLOCK_OrnamentalDingbats = new UnicodeBlock("OrnamentalDingbats", 0x0001f650, 0x0001f67f);
    /**
     * The Unicode block TransportandMapSymbols
     */
    public static final UnicodeBlock BLOCK_TransportandMapSymbols = new UnicodeBlock("TransportandMapSymbols", 0x0001f680, 0x0001f6ff);
    /**
     * The Unicode block AlchemicalSymbols
     */
    public static final UnicodeBlock BLOCK_AlchemicalSymbols = new UnicodeBlock("AlchemicalSymbols", 0x0001f700, 0x0001f77f);
    /**
     * The Unicode block GeometricShapesExtended
     */
    public static final UnicodeBlock BLOCK_GeometricShapesExtended = new UnicodeBlock("GeometricShapesExtended", 0x0001f780, 0x0001f7ff);
    /**
     * The Unicode block SupplementalArrows-C
     */
    public static final UnicodeBlock BLOCK_SupplementalArrowsC = new UnicodeBlock("SupplementalArrows-C", 0x0001f800, 0x0001f8ff);
    /**
     * The Unicode block SupplementalSymbolsandPictographs
     */
    public static final UnicodeBlock BLOCK_SupplementalSymbolsandPictographs = new UnicodeBlock("SupplementalSymbolsandPictographs", 0x0001f900, 0x0001f9ff);
    /**
     * The Unicode block CJKUnifiedIdeographsExtensionB
     */
    public static final UnicodeBlock BLOCK_CJKUnifiedIdeographsExtensionB = new UnicodeBlock("CJKUnifiedIdeographsExtensionB", 0x00020000, 0x0002a6df);
    /**
     * The Unicode block CJKUnifiedIdeographsExtensionC
     */
    public static final UnicodeBlock BLOCK_CJKUnifiedIdeographsExtensionC = new UnicodeBlock("CJKUnifiedIdeographsExtensionC", 0x0002a700, 0x0002b73f);
    /**
     * The Unicode block CJKUnifiedIdeographsExtensionD
     */
    public static final UnicodeBlock BLOCK_CJKUnifiedIdeographsExtensionD = new UnicodeBlock("CJKUnifiedIdeographsExtensionD", 0x0002b740, 0x0002b81f);
    /**
     * The Unicode block CJKUnifiedIdeographsExtensionE
     */
    public static final UnicodeBlock BLOCK_CJKUnifiedIdeographsExtensionE = new UnicodeBlock("CJKUnifiedIdeographsExtensionE", 0x0002b820, 0x0002ceaf);
    /**
     * The Unicode block CJKUnifiedIdeographsExtensionF
     */
    public static final UnicodeBlock BLOCK_CJKUnifiedIdeographsExtensionF = new UnicodeBlock("CJKUnifiedIdeographsExtensionF", 0x0002ceb0, 0x0002ebef);
    /**
     * The Unicode block CJKCompatibilityIdeographsSupplement
     */
    public static final UnicodeBlock BLOCK_CJKCompatibilityIdeographsSupplement = new UnicodeBlock("CJKCompatibilityIdeographsSupplement", 0x0002f800, 0x0002fa1f);
    /**
     * The Unicode block Tags
     */
    public static final UnicodeBlock BLOCK_Tags = new UnicodeBlock("Tags", 0x000e0000, 0x000e007f);
    /**
     * The Unicode block VariationSelectorsSupplement
     */
    public static final UnicodeBlock BLOCK_VariationSelectorsSupplement = new UnicodeBlock("VariationSelectorsSupplement", 0x000e0100, 0x000e01ef);
    /**
     * The Unicode block SupplementaryPrivateUseArea-A
     */
    public static final UnicodeBlock BLOCK_SupplementaryPrivateUseAreaA = new UnicodeBlock("SupplementaryPrivateUseArea-A", 0x000f0000, 0x000fffff);
    /**
     * The Unicode block SupplementaryPrivateUseArea-B
     */
    public static final UnicodeBlock BLOCK_SupplementaryPrivateUseAreaB = new UnicodeBlock("SupplementaryPrivateUseArea-B", 0x00100000, 0x0010ffff);

    /**
     * The database of Unicode blocks accessible by names
     */
    private static final Map<String, UnicodeBlock> db = new HashMap<>();

    static {
        db.put("BasicLatin", BLOCK_BasicLatin);
        db.put("Latin-1Supplement", BLOCK_Latin1Supplement);
        db.put("LatinExtended-A", BLOCK_LatinExtendedA);
        db.put("LatinExtended-B", BLOCK_LatinExtendedB);
        db.put("IPAExtensions", BLOCK_IPAExtensions);
        db.put("SpacingModifierLetters", BLOCK_SpacingModifierLetters);
        db.put("CombiningDiacriticalMarks", BLOCK_CombiningDiacriticalMarks);
        db.put("GreekandCoptic", BLOCK_GreekandCoptic);
        db.put("Cyrillic", BLOCK_Cyrillic);
        db.put("CyrillicSupplement", BLOCK_CyrillicSupplement);
        db.put("Armenian", BLOCK_Armenian);
        db.put("Hebrew", BLOCK_Hebrew);
        db.put("Arabic", BLOCK_Arabic);
        db.put("Syriac", BLOCK_Syriac);
        db.put("ArabicSupplement", BLOCK_ArabicSupplement);
        db.put("Thaana", BLOCK_Thaana);
        db.put("NKo", BLOCK_NKo);
        db.put("Samaritan", BLOCK_Samaritan);
        db.put("Mandaic", BLOCK_Mandaic);
        db.put("SyriacSupplement", BLOCK_SyriacSupplement);
        db.put("ArabicExtended-A", BLOCK_ArabicExtendedA);
        db.put("Devanagari", BLOCK_Devanagari);
        db.put("Bengali", BLOCK_Bengali);
        db.put("Gurmukhi", BLOCK_Gurmukhi);
        db.put("Gujarati", BLOCK_Gujarati);
        db.put("Oriya", BLOCK_Oriya);
        db.put("Tamil", BLOCK_Tamil);
        db.put("Telugu", BLOCK_Telugu);
        db.put("Kannada", BLOCK_Kannada);
        db.put("Malayalam", BLOCK_Malayalam);
        db.put("Sinhala", BLOCK_Sinhala);
        db.put("Thai", BLOCK_Thai);
        db.put("Lao", BLOCK_Lao);
        db.put("Tibetan", BLOCK_Tibetan);
        db.put("Myanmar", BLOCK_Myanmar);
        db.put("Georgian", BLOCK_Georgian);
        db.put("HangulJamo", BLOCK_HangulJamo);
        db.put("Ethiopic", BLOCK_Ethiopic);
        db.put("EthiopicSupplement", BLOCK_EthiopicSupplement);
        db.put("Cherokee", BLOCK_Cherokee);
        db.put("UnifiedCanadianAboriginalSyllabics", BLOCK_UnifiedCanadianAboriginalSyllabics);
        db.put("Ogham", BLOCK_Ogham);
        db.put("Runic", BLOCK_Runic);
        db.put("Tagalog", BLOCK_Tagalog);
        db.put("Hanunoo", BLOCK_Hanunoo);
        db.put("Buhid", BLOCK_Buhid);
        db.put("Tagbanwa", BLOCK_Tagbanwa);
        db.put("Khmer", BLOCK_Khmer);
        db.put("Mongolian", BLOCK_Mongolian);
        db.put("UnifiedCanadianAboriginalSyllabicsExtended", BLOCK_UnifiedCanadianAboriginalSyllabicsExtended);
        db.put("Limbu", BLOCK_Limbu);
        db.put("TaiLe", BLOCK_TaiLe);
        db.put("NewTaiLue", BLOCK_NewTaiLue);
        db.put("KhmerSymbols", BLOCK_KhmerSymbols);
        db.put("Buginese", BLOCK_Buginese);
        db.put("TaiTham", BLOCK_TaiTham);
        db.put("CombiningDiacriticalMarksExtended", BLOCK_CombiningDiacriticalMarksExtended);
        db.put("Balinese", BLOCK_Balinese);
        db.put("Sundanese", BLOCK_Sundanese);
        db.put("Batak", BLOCK_Batak);
        db.put("Lepcha", BLOCK_Lepcha);
        db.put("OlChiki", BLOCK_OlChiki);
        db.put("CyrillicExtended-C", BLOCK_CyrillicExtendedC);
        db.put("SundaneseSupplement", BLOCK_SundaneseSupplement);
        db.put("VedicExtensions", BLOCK_VedicExtensions);
        db.put("PhoneticExtensions", BLOCK_PhoneticExtensions);
        db.put("PhoneticExtensionsSupplement", BLOCK_PhoneticExtensionsSupplement);
        db.put("CombiningDiacriticalMarksSupplement", BLOCK_CombiningDiacriticalMarksSupplement);
        db.put("LatinExtendedAdditional", BLOCK_LatinExtendedAdditional);
        db.put("GreekExtended", BLOCK_GreekExtended);
        db.put("GeneralPunctuation", BLOCK_GeneralPunctuation);
        db.put("SuperscriptsandSubscripts", BLOCK_SuperscriptsandSubscripts);
        db.put("CurrencySymbols", BLOCK_CurrencySymbols);
        db.put("CombiningDiacriticalMarksforSymbols", BLOCK_CombiningDiacriticalMarksforSymbols);
        db.put("LetterlikeSymbols", BLOCK_LetterlikeSymbols);
        db.put("NumberForms", BLOCK_NumberForms);
        db.put("Arrows", BLOCK_Arrows);
        db.put("MathematicalOperators", BLOCK_MathematicalOperators);
        db.put("MiscellaneousTechnical", BLOCK_MiscellaneousTechnical);
        db.put("ControlPictures", BLOCK_ControlPictures);
        db.put("OpticalCharacterRecognition", BLOCK_OpticalCharacterRecognition);
        db.put("EnclosedAlphanumerics", BLOCK_EnclosedAlphanumerics);
        db.put("BoxDrawing", BLOCK_BoxDrawing);
        db.put("BlockElements", BLOCK_BlockElements);
        db.put("GeometricShapes", BLOCK_GeometricShapes);
        db.put("MiscellaneousSymbols", BLOCK_MiscellaneousSymbols);
        db.put("Dingbats", BLOCK_Dingbats);
        db.put("MiscellaneousMathematicalSymbols-A", BLOCK_MiscellaneousMathematicalSymbolsA);
        db.put("SupplementalArrows-A", BLOCK_SupplementalArrowsA);
        db.put("BraillePatterns", BLOCK_BraillePatterns);
        db.put("SupplementalArrows-B", BLOCK_SupplementalArrowsB);
        db.put("MiscellaneousMathematicalSymbols-B", BLOCK_MiscellaneousMathematicalSymbolsB);
        db.put("SupplementalMathematicalOperators", BLOCK_SupplementalMathematicalOperators);
        db.put("MiscellaneousSymbolsandArrows", BLOCK_MiscellaneousSymbolsandArrows);
        db.put("Glagolitic", BLOCK_Glagolitic);
        db.put("LatinExtended-C", BLOCK_LatinExtendedC);
        db.put("Coptic", BLOCK_Coptic);
        db.put("GeorgianSupplement", BLOCK_GeorgianSupplement);
        db.put("Tifinagh", BLOCK_Tifinagh);
        db.put("EthiopicExtended", BLOCK_EthiopicExtended);
        db.put("CyrillicExtended-A", BLOCK_CyrillicExtendedA);
        db.put("SupplementalPunctuation", BLOCK_SupplementalPunctuation);
        db.put("CJKRadicalsSupplement", BLOCK_CJKRadicalsSupplement);
        db.put("KangxiRadicals", BLOCK_KangxiRadicals);
        db.put("IdeographicDescriptionCharacters", BLOCK_IdeographicDescriptionCharacters);
        db.put("CJKSymbolsandPunctuation", BLOCK_CJKSymbolsandPunctuation);
        db.put("Hiragana", BLOCK_Hiragana);
        db.put("Katakana", BLOCK_Katakana);
        db.put("Bopomofo", BLOCK_Bopomofo);
        db.put("HangulCompatibilityJamo", BLOCK_HangulCompatibilityJamo);
        db.put("Kanbun", BLOCK_Kanbun);
        db.put("BopomofoExtended", BLOCK_BopomofoExtended);
        db.put("CJKStrokes", BLOCK_CJKStrokes);
        db.put("KatakanaPhoneticExtensions", BLOCK_KatakanaPhoneticExtensions);
        db.put("EnclosedCJKLettersandMonths", BLOCK_EnclosedCJKLettersandMonths);
        db.put("CJKCompatibility", BLOCK_CJKCompatibility);
        db.put("CJKUnifiedIdeographsExtensionA", BLOCK_CJKUnifiedIdeographsExtensionA);
        db.put("YijingHexagramSymbols", BLOCK_YijingHexagramSymbols);
        db.put("CJKUnifiedIdeographs", BLOCK_CJKUnifiedIdeographs);
        db.put("YiSyllables", BLOCK_YiSyllables);
        db.put("YiRadicals", BLOCK_YiRadicals);
        db.put("Lisu", BLOCK_Lisu);
        db.put("Vai", BLOCK_Vai);
        db.put("CyrillicExtended-B", BLOCK_CyrillicExtendedB);
        db.put("Bamum", BLOCK_Bamum);
        db.put("ModifierToneLetters", BLOCK_ModifierToneLetters);
        db.put("LatinExtended-D", BLOCK_LatinExtendedD);
        db.put("SylotiNagri", BLOCK_SylotiNagri);
        db.put("CommonIndicNumberForms", BLOCK_CommonIndicNumberForms);
        db.put("Phags-pa", BLOCK_Phagspa);
        db.put("Saurashtra", BLOCK_Saurashtra);
        db.put("DevanagariExtended", BLOCK_DevanagariExtended);
        db.put("KayahLi", BLOCK_KayahLi);
        db.put("Rejang", BLOCK_Rejang);
        db.put("HangulJamoExtended-A", BLOCK_HangulJamoExtendedA);
        db.put("Javanese", BLOCK_Javanese);
        db.put("MyanmarExtended-B", BLOCK_MyanmarExtendedB);
        db.put("Cham", BLOCK_Cham);
        db.put("MyanmarExtended-A", BLOCK_MyanmarExtendedA);
        db.put("TaiViet", BLOCK_TaiViet);
        db.put("MeeteiMayekExtensions", BLOCK_MeeteiMayekExtensions);
        db.put("EthiopicExtended-A", BLOCK_EthiopicExtendedA);
        db.put("LatinExtended-E", BLOCK_LatinExtendedE);
        db.put("CherokeeSupplement", BLOCK_CherokeeSupplement);
        db.put("MeeteiMayek", BLOCK_MeeteiMayek);
        db.put("HangulSyllables", BLOCK_HangulSyllables);
        db.put("HangulJamoExtended-B", BLOCK_HangulJamoExtendedB);
        db.put("PrivateUseArea", BLOCK_PrivateUseArea);
        db.put("CJKCompatibilityIdeographs", BLOCK_CJKCompatibilityIdeographs);
        db.put("AlphabeticPresentationForms", BLOCK_AlphabeticPresentationForms);
        db.put("ArabicPresentationForms-A", BLOCK_ArabicPresentationFormsA);
        db.put("VariationSelectors", BLOCK_VariationSelectors);
        db.put("VerticalForms", BLOCK_VerticalForms);
        db.put("CombiningHalfMarks", BLOCK_CombiningHalfMarks);
        db.put("CJKCompatibilityForms", BLOCK_CJKCompatibilityForms);
        db.put("SmallFormVariants", BLOCK_SmallFormVariants);
        db.put("ArabicPresentationForms-B", BLOCK_ArabicPresentationFormsB);
        db.put("HalfwidthandFullwidthForms", BLOCK_HalfwidthandFullwidthForms);
        db.put("Specials", BLOCK_Specials);
        db.put("LinearBSyllabary", BLOCK_LinearBSyllabary);
        db.put("LinearBIdeograms", BLOCK_LinearBIdeograms);
        db.put("AegeanNumbers", BLOCK_AegeanNumbers);
        db.put("AncientGreekNumbers", BLOCK_AncientGreekNumbers);
        db.put("AncientSymbols", BLOCK_AncientSymbols);
        db.put("PhaistosDisc", BLOCK_PhaistosDisc);
        db.put("Lycian", BLOCK_Lycian);
        db.put("Carian", BLOCK_Carian);
        db.put("CopticEpactNumbers", BLOCK_CopticEpactNumbers);
        db.put("OldItalic", BLOCK_OldItalic);
        db.put("Gothic", BLOCK_Gothic);
        db.put("OldPermic", BLOCK_OldPermic);
        db.put("Ugaritic", BLOCK_Ugaritic);
        db.put("OldPersian", BLOCK_OldPersian);
        db.put("Deseret", BLOCK_Deseret);
        db.put("Shavian", BLOCK_Shavian);
        db.put("Osmanya", BLOCK_Osmanya);
        db.put("Osage", BLOCK_Osage);
        db.put("Elbasan", BLOCK_Elbasan);
        db.put("CaucasianAlbanian", BLOCK_CaucasianAlbanian);
        db.put("LinearA", BLOCK_LinearA);
        db.put("CypriotSyllabary", BLOCK_CypriotSyllabary);
        db.put("ImperialAramaic", BLOCK_ImperialAramaic);
        db.put("Palmyrene", BLOCK_Palmyrene);
        db.put("Nabataean", BLOCK_Nabataean);
        db.put("Hatran", BLOCK_Hatran);
        db.put("Phoenician", BLOCK_Phoenician);
        db.put("Lydian", BLOCK_Lydian);
        db.put("MeroiticHieroglyphs", BLOCK_MeroiticHieroglyphs);
        db.put("MeroiticCursive", BLOCK_MeroiticCursive);
        db.put("Kharoshthi", BLOCK_Kharoshthi);
        db.put("OldSouthArabian", BLOCK_OldSouthArabian);
        db.put("OldNorthArabian", BLOCK_OldNorthArabian);
        db.put("Manichaean", BLOCK_Manichaean);
        db.put("Avestan", BLOCK_Avestan);
        db.put("InscriptionalParthian", BLOCK_InscriptionalParthian);
        db.put("InscriptionalPahlavi", BLOCK_InscriptionalPahlavi);
        db.put("PsalterPahlavi", BLOCK_PsalterPahlavi);
        db.put("OldTurkic", BLOCK_OldTurkic);
        db.put("OldHungarian", BLOCK_OldHungarian);
        db.put("RumiNumeralSymbols", BLOCK_RumiNumeralSymbols);
        db.put("Brahmi", BLOCK_Brahmi);
        db.put("Kaithi", BLOCK_Kaithi);
        db.put("SoraSompeng", BLOCK_SoraSompeng);
        db.put("Chakma", BLOCK_Chakma);
        db.put("Mahajani", BLOCK_Mahajani);
        db.put("Sharada", BLOCK_Sharada);
        db.put("SinhalaArchaicNumbers", BLOCK_SinhalaArchaicNumbers);
        db.put("Khojki", BLOCK_Khojki);
        db.put("Multani", BLOCK_Multani);
        db.put("Khudawadi", BLOCK_Khudawadi);
        db.put("Grantha", BLOCK_Grantha);
        db.put("Newa", BLOCK_Newa);
        db.put("Tirhuta", BLOCK_Tirhuta);
        db.put("Siddham", BLOCK_Siddham);
        db.put("Modi", BLOCK_Modi);
        db.put("MongolianSupplement", BLOCK_MongolianSupplement);
        db.put("Takri", BLOCK_Takri);
        db.put("Ahom", BLOCK_Ahom);
        db.put("WarangCiti", BLOCK_WarangCiti);
        db.put("ZanabazarSquare", BLOCK_ZanabazarSquare);
        db.put("Soyombo", BLOCK_Soyombo);
        db.put("PauCinHau", BLOCK_PauCinHau);
        db.put("Bhaiksuki", BLOCK_Bhaiksuki);
        db.put("Marchen", BLOCK_Marchen);
        db.put("MasaramGondi", BLOCK_MasaramGondi);
        db.put("Cuneiform", BLOCK_Cuneiform);
        db.put("CuneiformNumbersandPunctuation", BLOCK_CuneiformNumbersandPunctuation);
        db.put("EarlyDynasticCuneiform", BLOCK_EarlyDynasticCuneiform);
        db.put("EgyptianHieroglyphs", BLOCK_EgyptianHieroglyphs);
        db.put("AnatolianHieroglyphs", BLOCK_AnatolianHieroglyphs);
        db.put("BamumSupplement", BLOCK_BamumSupplement);
        db.put("Mro", BLOCK_Mro);
        db.put("BassaVah", BLOCK_BassaVah);
        db.put("PahawhHmong", BLOCK_PahawhHmong);
        db.put("Miao", BLOCK_Miao);
        db.put("IdeographicSymbolsandPunctuation", BLOCK_IdeographicSymbolsandPunctuation);
        db.put("Tangut", BLOCK_Tangut);
        db.put("TangutComponents", BLOCK_TangutComponents);
        db.put("KanaSupplement", BLOCK_KanaSupplement);
        db.put("KanaExtended-A", BLOCK_KanaExtendedA);
        db.put("Nushu", BLOCK_Nushu);
        db.put("Duployan", BLOCK_Duployan);
        db.put("ShorthandFormatControls", BLOCK_ShorthandFormatControls);
        db.put("ByzantineMusicalSymbols", BLOCK_ByzantineMusicalSymbols);
        db.put("MusicalSymbols", BLOCK_MusicalSymbols);
        db.put("AncientGreekMusicalNotation", BLOCK_AncientGreekMusicalNotation);
        db.put("TaiXuanJingSymbols", BLOCK_TaiXuanJingSymbols);
        db.put("CountingRodNumerals", BLOCK_CountingRodNumerals);
        db.put("MathematicalAlphanumericSymbols", BLOCK_MathematicalAlphanumericSymbols);
        db.put("SuttonSignWriting", BLOCK_SuttonSignWriting);
        db.put("GlagoliticSupplement", BLOCK_GlagoliticSupplement);
        db.put("MendeKikakui", BLOCK_MendeKikakui);
        db.put("Adlam", BLOCK_Adlam);
        db.put("ArabicMathematicalAlphabeticSymbols", BLOCK_ArabicMathematicalAlphabeticSymbols);
        db.put("MahjongTiles", BLOCK_MahjongTiles);
        db.put("DominoTiles", BLOCK_DominoTiles);
        db.put("PlayingCards", BLOCK_PlayingCards);
        db.put("EnclosedAlphanumericSupplement", BLOCK_EnclosedAlphanumericSupplement);
        db.put("EnclosedIdeographicSupplement", BLOCK_EnclosedIdeographicSupplement);
        db.put("MiscellaneousSymbolsandPictographs", BLOCK_MiscellaneousSymbolsandPictographs);
        db.put("Emoticons", BLOCK_Emoticons);
        db.put("OrnamentalDingbats", BLOCK_OrnamentalDingbats);
        db.put("TransportandMapSymbols", BLOCK_TransportandMapSymbols);
        db.put("AlchemicalSymbols", BLOCK_AlchemicalSymbols);
        db.put("GeometricShapesExtended", BLOCK_GeometricShapesExtended);
        db.put("SupplementalArrows-C", BLOCK_SupplementalArrowsC);
        db.put("SupplementalSymbolsandPictographs", BLOCK_SupplementalSymbolsandPictographs);
        db.put("CJKUnifiedIdeographsExtensionB", BLOCK_CJKUnifiedIdeographsExtensionB);
        db.put("CJKUnifiedIdeographsExtensionC", BLOCK_CJKUnifiedIdeographsExtensionC);
        db.put("CJKUnifiedIdeographsExtensionD", BLOCK_CJKUnifiedIdeographsExtensionD);
        db.put("CJKUnifiedIdeographsExtensionE", BLOCK_CJKUnifiedIdeographsExtensionE);
        db.put("CJKUnifiedIdeographsExtensionF", BLOCK_CJKUnifiedIdeographsExtensionF);
        db.put("CJKCompatibilityIdeographsSupplement", BLOCK_CJKCompatibilityIdeographsSupplement);
        db.put("Tags", BLOCK_Tags);
        db.put("VariationSelectorsSupplement", BLOCK_VariationSelectorsSupplement);
        db.put("SupplementaryPrivateUseArea-A", BLOCK_SupplementaryPrivateUseAreaA);
        db.put("SupplementaryPrivateUseArea-B", BLOCK_SupplementaryPrivateUseAreaB);
    }

    /**
     * Gets the block with the given name
     *
     * @param name A Unicode block name
     * @return The corresponding block, or null if it does not exists
     */
    public static UnicodeBlock getBlock(String name) {
        return db.get(name);
    }
}
