using System.Collections.Generic;

namespace Hime.Parsers.CF.LR
{
    class ItemSetReductionsRNGLR1 : ItemSetReductions
    {
        private List<ItemSetActionRNReduce> actionReductions;

        public override ICollection<ItemSetActionReduce> Reductions
        {
            get
            {
                List<ItemSetActionReduce> Temp = new List<ItemSetActionReduce>();
                foreach (ItemSetActionRNReduce action in actionReductions)
                    Temp.Add(action);
                return Temp;
            }
        }
        public override TerminalSet ExpectedTerminals
        {
            get
            {
                TerminalSet Set = new TerminalSet();
                foreach (ItemSetActionReduce Reduction in actionReductions)
                    Set.Add(Reduction.Lookahead);
                return Set;
            }
        }

        public ItemSetReductionsRNGLR1()
        {
            actionReductions = new List<ItemSetActionRNReduce>();
        }

        public override void Build(ItemSet Set)
        {
            // Build shift actions
            foreach (Symbol Next in Set.Children.Keys)
            {
                List<ItemSetAction> Actions = new List<ItemSetAction>();
                Actions.Add(new ItemSetActionShift(Next, Set.Children[Next]));
            }

            // Redutions dictionnary for the given set
            Dictionary<Terminal, ItemLR1> Reductions = new Dictionary<Terminal, ItemLR1>();
            // Construct reductions
            foreach (ItemLR1 Item in Set.Items)
            {
                // Check for right nulled reduction
                if (Item.Action == ItemAction.Shift && !Item.BaseRule.Definition.GetChoiceAtIndex(Item.DotPosition).Firsts.Contains(TerminalEpsilon.Instance))
                    continue;
                bool rightnulled = (Item.DotPosition != Item.BaseRule.Definition.GetChoiceAtIndex(0).Length);
                // There is already a shift action for the lookahead => conflict
                if (Set.Children.ContainsKey(Item.Lookahead))
                {
                    ItemSetReductionsLR1.HandleConflict_ShiftReduce(typeof(MethodRNGLR1), conflicts, Item, Set, Item.Lookahead);
                    ItemSetActionRNReduce Reduction = new ItemSetActionRNReduce(Item.Lookahead, Item.BaseRule, Item.DotPosition);
                    actionReductions.Add(Reduction);
                }
                // There is already a reduction action for the lookahead => conflict
                else if (Reductions.ContainsKey(Item.Lookahead))
                {
                    ItemSetReductionsLR1.HandleConflict_ReduceReduce(typeof(MethodRNGLR1), conflicts, Item, Reductions[Item.Lookahead], Set, Item.Lookahead);
                    ItemSetActionRNReduce Reduction = new ItemSetActionRNReduce(Item.Lookahead, Item.BaseRule, Item.DotPosition);
                    actionReductions.Add(Reduction);
                }
                else // No conflict
                {
                    // hide conflicts generated by reducing using right-nulled rules
                    if (!rightnulled)
                        Reductions.Add(Item.Lookahead, Item);
                    ItemSetActionRNReduce Reduction = new ItemSetActionRNReduce(Item.Lookahead, Item.BaseRule, Item.DotPosition);
                    actionReductions.Add(Reduction);
                }
            }
        }
    }
}
