using System.Collections.Generic;

namespace Hime.Parsers.CF.LR
{
    class StateReductionsRNGLR1 : StateReductions
    {
        public override TerminalSet ExpectedTerminals
        {
            get
            {
                TerminalSet Set = new TerminalSet();
                foreach (StateActionReduce Reduction in this)
                    Set.Add(Reduction.Lookahead);
                return Set;
            }
        }

        public StateReductionsRNGLR1() { }

        public override void Build(State Set)
        {
            // Build shift actions
            foreach (Symbol Next in Set.Children.Keys)
            {
                List<StateAction> Actions = new List<StateAction>();
                Actions.Add(new StateActionShift(Next, Set.Children[Next]));
            }

            // Redutions dictionnary for the given set
            Dictionary<Terminal, ItemLR1> Reductions = new Dictionary<Terminal, ItemLR1>();
            // Construct reductions
            foreach (ItemLR1 Item in Set.Items)
            {
                // Check for right nulled reduction
                if (Item.Action == ItemAction.Shift && !Item.BaseRule.Definition.GetChoiceAtIndex(Item.DotPosition).Firsts.Contains(TerminalEpsilon.Instance))
                    continue;
                bool rightnulled = (Item.DotPosition != Item.BaseRule.Definition.GetChoiceAtIndex(0).Length);
                // There is already a shift action for the lookahead => conflict
                if (Set.Children.ContainsKey(Item.Lookahead))
                {
                    StateReductionsLR1.HandleConflict_ShiftReduce("RNGLR(1)", conflicts, Item, Set, Item.Lookahead);
                    StateActionRNReduce Reduction = new StateActionRNReduce(Item.Lookahead, Item.BaseRule, Item.DotPosition);
                    this.Add(Reduction);
                }
                // There is already a reduction action for the lookahead => conflict
                else if (Reductions.ContainsKey(Item.Lookahead))
                {
                    StateReductionsLR1.HandleConflict_ReduceReduce("RNGLR(1)", conflicts, Item, Reductions[Item.Lookahead], Set, Item.Lookahead);
                    StateActionRNReduce Reduction = new StateActionRNReduce(Item.Lookahead, Item.BaseRule, Item.DotPosition);
                    this.Add(Reduction);
                }
                else // No conflict
                {
                    // hide conflicts generated by reducing using right-nulled rules
                    if (!rightnulled)
                        Reductions.Add(Item.Lookahead, Item);
                    StateActionRNReduce Reduction = new StateActionRNReduce(Item.Lookahead, Item.BaseRule, Item.DotPosition);
                    this.Add(Reduction);
                }
            }
        }
    }
}
